.PHONY: all build run clean proto generate

all: build

{{- if .IsHTML}}
build:
	@mkdir -p bin
	go build -o bin/server main.go

run:
	go run main.go
{{- else}}
generate:
	templ generate

build: generate
	@mkdir -p bin
	go build -o bin/server main.go

run: generate
	go run main.go
{{- end}}

clean:
	rm -rf bin

proto:
	buf generate --path internal/adapters/grpc/pb
