package generator

// domainTmpl generates internal/core/domain/{model}.go
// Uses scaffold markers so struct fields can be updated without losing Validate().
const domainTmpl = `package domain
{{- if .NeedsTimeImport}}

import "time"
{{- end}}
{{- if .NeedsJSONImport}}

import "encoding/json"
{{- end}}

type {{.Name}} struct {
	// scaffold:fields:start
{{- range .Fields}}
	{{.GoName}} {{.GoType}} ` + "`" + `json:"{{.Name}}"` + "`" + `
{{- end}}
	ID        string    ` + "`" + `json:"id"` + "`" + `
	CreatedAt time.Time ` + "`" + `json:"created_at"` + "`" + `
	UpdatedAt time.Time ` + "`" + `json:"updated_at"` + "`" + `
	// scaffold:fields:end
}

// scaffold:method:GetID:start
func ({{.Receiver}} {{.Name}}) GetID() string { return {{.Receiver}}.ID }
// scaffold:method:GetID:end

// scaffold:method:WithID:start
func ({{.Receiver}} {{.Name}}) WithID(id string) {{.Name}} { {{.Receiver}}.ID = id; return {{.Receiver}} }
// scaffold:method:WithID:end

// Validate enforces business rules on {{.Name}}.
// This method is never overwritten by scaffold — add your rules here.
func ({{.Receiver}} {{.Name}}) Validate() error {
	return nil
}
`

// portsTmpl generates internal/core/ports/{model}.go
const portsTmpl = `// Code generated by scaffold. DO NOT EDIT.

package ports

import "{{.ModulePath}}/internal/core/domain"

type {{.Name}}Store interface {
	CRUDStore[domain.{{.Name}}]
}

type {{.Name}}Service interface {
	CRUDService[domain.{{.Name}}]
}
`

// serviceGenTmpl generates internal/core/services/{model}_service_gen.go
const serviceGenTmpl = `// Code generated by scaffold. DO NOT EDIT.

package services

import (
	"context"
	"log/slog"

	"{{.ModulePath}}/internal/core/domain"
	"{{.ModulePath}}/internal/core/ports"
)

type {{.Name}}Service struct {
	store  ports.{{.Name}}Store
	logger *slog.Logger
}

func New{{.Name}}Service(store ports.{{.Name}}Store, logger *slog.Logger) *{{.Name}}Service {
	return &{{.Name}}Service{store: store, logger: logger}
}

func (s *{{.Name}}Service) Get(ctx context.Context, id string) (*domain.{{.Name}}, error) {
	s.logger.DebugContext(ctx, "fetching {{.Lower}}", "id", id)
	v, err := s.store.Get(ctx, id)
	if err != nil {
		return nil, err
	}
	return &v, nil
}

func (s *{{.Name}}Service) List(ctx context.Context, limit, offset int) ([]domain.{{.Name}}, error) {
	s.logger.DebugContext(ctx, "listing {{.Lower}}s", "limit", limit, "offset", offset)
	return s.store.List(ctx, limit, offset)
}

func (s *{{.Name}}Service) Create(ctx context.Context, p domain.{{.Name}}) (*domain.{{.Name}}, error) {
	s.logger.DebugContext(ctx, "creating {{.Lower}}")
	if err := p.Validate(); err != nil {
		return nil, err
	}
	v, err := s.store.Create(ctx, p)
	if err != nil {
		return nil, err
	}
	return &v, nil
}

func (s *{{.Name}}Service) Update(ctx context.Context, p domain.{{.Name}}) (*domain.{{.Name}}, error) {
	s.logger.DebugContext(ctx, "updating {{.Lower}}", "id", p.ID)
	if err := p.Validate(); err != nil {
		return nil, err
	}
	v, err := s.store.Update(ctx, p)
	if err != nil {
		return nil, err
	}
	return &v, nil
}

func (s *{{.Name}}Service) Delete(ctx context.Context, id string) error {
	s.logger.DebugContext(ctx, "deleting {{.Lower}}", "id", id)
	return s.store.Delete(ctx, id)
}
`

// serviceUserTmpl generates internal/core/services/{model}_service.go (created once)
const serviceUserTmpl = `package services

// {{.Name}}Service custom methods.
// This file is never overwritten by scaffold — add your business logic here.
`

// storeGenTmpl generates internal/adapters/store/{model}_store_gen.go
const storeGenTmpl = `// Code generated by scaffold. DO NOT EDIT.

package store

import (
	"context"
	"database/sql"
	"errors"
{{- if .NeedsJSON}}
	"encoding/json"
{{- end}}

	"{{.ModulePath}}/internal/core/domain"
	"{{.ModulePath}}/internal/core/ports"
)

// {{.Name}}Store implements ports.CRUDStore[domain.{{.Name}}].
type {{.Name}}Store struct{ *Store }

var _ ports.CRUDStore[domain.{{.Name}}] = (*{{.Name}}Store)(nil)

const (
	sql{{.Name}}Get    = ` + "`" + `SELECT {{.SelectCols}} FROM {{.TableName}} WHERE id = ?` + "`" + `
	sql{{.Name}}List   = ` + "`" + `SELECT {{.SelectCols}} FROM {{.TableName}} LIMIT ? OFFSET ?` + "`" + `
	sql{{.Name}}Create = ` + "`" + `INSERT INTO {{.TableName}} ({{.InsertCols}}) VALUES ({{.InsertPlaceholders}}) RETURNING id, created_at, updated_at` + "`" + `
	sql{{.Name}}Update = ` + "`" + `UPDATE {{.TableName}} SET {{.UpdateSet}}, updated_at = CURRENT_TIMESTAMP WHERE id = ? RETURNING created_at, updated_at` + "`" + `
	sql{{.Name}}Delete = ` + "`" + `DELETE FROM {{.TableName}} WHERE id = ?` + "`" + `
)

{{template "scanFunc" .}}

func (s *{{.Name}}Store) Get(ctx context.Context, id string) (domain.{{.Name}}, error) {
	const op = "{{.Name}}Store.Get"
	row := s.db.QueryRowContext(ctx, sql{{.Name}}Get, id)
	notFoundErr := &domain.NotFoundError{Entity: "{{.Name}}", ID: id}
	return queryRow(row, notFoundErr, op, func(r *sql.Row) (domain.{{.Name}}, error) {
		return scan{{.Name}}(r)
	})
}

func (s *{{.Name}}Store) List(ctx context.Context, limit, offset int) ([]domain.{{.Name}}, error) {
	const op = "{{.Name}}Store.List"
	rows, err := s.db.QueryContext(ctx, sql{{.Name}}List, limit, offset)
	if err != nil {
		return nil, DecorateError(err, op)
	}
	return collectRows(rows, op, func(r *sql.Rows) (domain.{{.Name}}, error) {
		return scan{{.Name}}Rows(r)
	})
}

func (s *{{.Name}}Store) Create(ctx context.Context, p domain.{{.Name}}) (domain.{{.Name}}, error) {
	const op = "{{.Name}}Store.Create"
	row := s.db.QueryRowContext(ctx, sql{{.Name}}Create, {{.CreateArgs}})
	if err := row.Scan(&p.ID, &p.CreatedAt, &p.UpdatedAt); err != nil {
		if IsUniqueViolation(err) {
			return domain.{{.Name}}{}, &domain.AlreadyExistsError{Entity: "{{.Name}}"}
		}
		return domain.{{.Name}}{}, DecorateError(err, op)
	}
	return p, nil
}

func (s *{{.Name}}Store) Update(ctx context.Context, p domain.{{.Name}}) (domain.{{.Name}}, error) {
	const op = "{{.Name}}Store.Update"
	row := s.db.QueryRowContext(ctx, sql{{.Name}}Update, {{.UpdateArgs}})
	if err := row.Scan(&p.CreatedAt, &p.UpdatedAt); err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return domain.{{.Name}}{}, &domain.NotFoundError{Entity: "{{.Name}}", ID: p.ID}
		}
		if IsUniqueViolation(err) {
			return domain.{{.Name}}{}, &domain.AlreadyExistsError{Entity: "{{.Name}}"}
		}
		return domain.{{.Name}}{}, DecorateError(err, op)
	}
	return p, nil
}

func (s *{{.Name}}Store) Delete(ctx context.Context, id string) error {
	const op = "{{.Name}}Store.Delete"
	res, err := s.db.ExecContext(ctx, sql{{.Name}}Delete, id)
	if err != nil {
		return DecorateError(err, op)
	}
	n, err := res.RowsAffected()
	if err != nil {
		return DecorateError(err, op)
	}
	if n == 0 {
		return &domain.NotFoundError{Entity: "{{.Name}}", ID: id}
	}
	return nil
}
`

// scanFuncTmpl is a sub-template rendered inside storeGenTmpl.
// Handles regular fields and json.RawMessage two-step scanning.
const scanFuncTmpl = `{{define "scanFunc"}}
func scan{{.Name}}(r *sql.Row) (domain.{{.Name}}, error) {
	var p domain.{{.Name}}
{{- range .Fields}}{{if .IsJSON}}
	var {{.GoName}}Bytes []byte
{{- end}}{{end}}
	err := r.Scan({{.ScanArgs}})
	if err != nil {
		return domain.{{.Name}}{}, err
	}
{{- range .Fields}}{{if .IsJSON}}
	if {{.GoName}}Bytes != nil {
		p.{{.GoName}} = json.RawMessage({{.GoName}}Bytes)
	}
{{- end}}{{end}}
	return p, nil
}

func scan{{.Name}}Rows(r *sql.Rows) (domain.{{.Name}}, error) {
	var p domain.{{.Name}}
{{- range .Fields}}{{if .IsJSON}}
	var {{.GoName}}Bytes []byte
{{- end}}{{end}}
	err := r.Scan({{.ScanArgs}})
	if err != nil {
		return domain.{{.Name}}{}, err
	}
{{- range .Fields}}{{if .IsJSON}}
	if {{.GoName}}Bytes != nil {
		p.{{.GoName}} = json.RawMessage({{.GoName}}Bytes)
	}
{{- end}}{{end}}
	return p, nil
}
{{end}}`

// storeUserTmpl generates internal/adapters/store/{model}_store.go (created once)
const storeUserTmpl = `package store

// {{.Name}} custom store methods.
// This file is never overwritten by scaffold — add your SQL queries here.

// Example:
// func (s *{{.Name}}Store) CustomMethod(ctx context.Context) ([]domain.{{.Name}}, error) {
// 	return nil, nil
// }
`

// schemaTmpl generates the SQL block inserted into schema.sql
const schemaTmpl = `-- scaffold:table:{{.Name}}:start
CREATE TABLE IF NOT EXISTS {{.TableName}} (
    {{.IDDef}},
{{- range .Fields}}
    {{.Name}} {{.SQLType}}{{if .NotNull}} NOT NULL{{end}}{{.SQLModifiers}},
{{- end}}
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TRIGGER IF NOT EXISTS trg_{{.TableName}}_updated_at
AFTER UPDATE ON {{.TableName}}
FOR EACH ROW
WHEN NEW.updated_at <= OLD.updated_at
BEGIN
    UPDATE {{.TableName}} SET updated_at = CURRENT_TIMESTAMP WHERE id = OLD.id;
END;
-- scaffold:table:{{.Name}}:end`

// migrationCreateTmpl generates the initial CREATE TABLE migration (goose format)
const migrationCreateTmpl = `-- +goose Up
CREATE TABLE IF NOT EXISTS {{.TableName}} (
    {{.IDDef}},
{{- range .Fields}}
    {{.Name}} {{.SQLType}}{{if .NotNull}} NOT NULL{{end}}{{.SQLModifiers}},
{{- end}}
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- +goose StatementBegin
CREATE TRIGGER IF NOT EXISTS trg_{{.TableName}}_updated_at
AFTER UPDATE ON {{.TableName}}
FOR EACH ROW
WHEN NEW.updated_at <= OLD.updated_at
BEGIN
    UPDATE {{.TableName}} SET updated_at = CURRENT_TIMESTAMP WHERE id = OLD.id;
END;
-- +goose StatementEnd

-- +goose Down
DROP TRIGGER IF EXISTS trg_{{.TableName}}_updated_at;
DROP TABLE IF EXISTS {{.TableName}};
`

// migrationAddColTmpl generates ALTER TABLE ADD COLUMN migration
const migrationAddColTmpl = `-- +goose Up
{{- range .Added}}
ALTER TABLE {{$.TableName}} ADD COLUMN {{.Name}} {{.SQLType}}{{if .NotNull}} NOT NULL{{end}}{{.SQLModifiers}};
{{- end}}

-- +goose Down
{{- range .Added}}
ALTER TABLE {{$.TableName}} DROP COLUMN {{.Name}};
{{- end}}
`

// migrationDropColTmpl generates ALTER TABLE DROP COLUMN migration
const migrationDropColTmpl = `-- +goose Up
{{- range .Removed}}
ALTER TABLE {{$.TableName}} DROP COLUMN {{.Name}};
{{- end}}

-- +goose Down
{{- range .Removed}}
ALTER TABLE {{$.TableName}} ADD COLUMN {{.Name}} {{.SQLType}}{{if .NotNull}} NOT NULL{{end}}{{.SQLModifiers}};
{{- end}}
`

// migrationDropTableTmpl generates the DROP TABLE migration for destroy
const migrationDropTableTmpl = `-- +goose Up
DROP TRIGGER IF EXISTS trg_{{.TableName}}_updated_at;
DROP TABLE IF EXISTS {{.TableName}};

-- +goose Down
CREATE TABLE IF NOT EXISTS {{.TableName}} (
    {{.IDDef}},
{{- range .Fields}}
    {{.Name}} {{.SQLType}}{{if .NotNull}} NOT NULL{{end}}{{.SQLModifiers}},
{{- end}}
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);
`

// registryTmpl fully regenerates internal/app/registry.go from the manifest
const registryTmpl = `// Code generated by scaffold. DO NOT EDIT.

package app

import (
	"database/sql"
	"log/slog"
{{- if .Models}}

	httpadapter "{{.ModulePath}}/internal/adapters/http"
	"{{.ModulePath}}/internal/adapters/store"
	"{{.ModulePath}}/internal/core/domain"
	"{{.ModulePath}}/internal/core/ports"
	"{{.ModulePath}}/internal/core/services"
{{- end}}
)

// Stores groups all database outbound adapters.
type Stores struct {
{{- range .Models}}
	{{.Name}} ports.{{.Name}}Store
{{- end}}
}

// Services groups all core business logic services.
type Services struct {
{{- range .Models}}
	{{.Name}} ports.{{.Name}}Service
{{- end}}
}

// Handlers groups all entry point HTTP controllers.
type Handlers struct {
{{- range .Models}}
	{{.Name}} *httpadapter.CRUDHandler[domain.{{.Name}}]
{{- end}}
}

// Registry is the unified Hexagonal container of the application.
type Registry struct {
	Stores   *Stores
	Services *Services
	Handlers *Handlers
}

// NewRegistry constructs and wires the entire dependency graph statically at startup.
func NewRegistry(db *sql.DB, logger *slog.Logger) *Registry {
{{- if .Models}}
	st := store.NewStore(db)
{{- end}}

	stores := &Stores{
{{- range .Models}}
		{{.Name}}: &store.{{.Name}}Store{Store: st},
{{- end}}
	}

	svcs := &Services{
{{- range .Models}}
		{{.Name}}: services.New{{.Name}}Service(stores.{{.Name}}, logger),
{{- end}}
	}

	handlers := &Handlers{
{{- range .Models}}
		{{.Name}}: httpadapter.NewCRUDHandler(svcs.{{.Name}}, "{{.Name}}", "", logger),
{{- end}}
	}

	return &Registry{
		Stores:   stores,
		Services: svcs,
		Handlers: handlers,
	}
}
`

// domainTmplPostgres generates internal/core/domain/{model}.go for Postgres projects
const domainTmplPostgres = `package domain
{{- if .NeedsTimeImport}}

import "time"
{{- end}}
{{- if .NeedsJSONImport}}

import "encoding/json"
{{- end}}

type {{.Name}} struct {
	// scaffold:fields:start
{{- range .Fields}}
	{{.GoName}} {{.GoType}} ` + "`" + `json:"{{.Name}}" db:"{{.Name}}"` + "`" + `
{{- end}}
	ID        string    ` + "`" + `json:"id" db:"id"` + "`" + `
	CreatedAt time.Time ` + "`" + `json:"created_at" db:"created_at"` + "`" + `
	UpdatedAt time.Time ` + "`" + `json:"updated_at" db:"updated_at"` + "`" + `
	// scaffold:fields:end
}

// scaffold:method:GetID:start
func ({{.Receiver}} {{.Name}}) GetID() string { return {{.Receiver}}.ID }
// scaffold:method:GetID:end

// scaffold:method:WithID:start
func ({{.Receiver}} {{.Name}}) WithID(id string) {{.Name}} { {{.Receiver}}.ID = id; return {{.Receiver}} }
// scaffold:method:WithID:end

// Validate enforces business rules on {{.Name}}.
// This method is never overwritten by scaffold — add your rules here.
func ({{.Receiver}} {{.Name}}) Validate() error {
	return nil
}
`

// storeGenTmplPostgres generates internal/adapters/store/{model}_store_gen.go for Postgres
const storeGenTmplPostgres = `// Code generated by scaffold. DO NOT EDIT.

package store

import (
	"context"
	"errors"

	"github.com/jackc/pgx/v5"
	"{{.ModulePath}}/internal/core/domain"
	"{{.ModulePath}}/internal/core/ports"
)

// {{.Name}}Store implements ports.CRUDStore[domain.{{.Name}}].
type {{.Name}}Store struct{ *Store }

var _ ports.CRUDStore[domain.{{.Name}}] = (*{{.Name}}Store)(nil)

const (
	sql{{.Name}}Get    = ` + "`" + `SELECT * FROM {{.TableName}} WHERE id = $1` + "`" + `
	sql{{.Name}}List   = ` + "`" + `SELECT * FROM {{.TableName}} LIMIT $1 OFFSET $2` + "`" + `
	sql{{.Name}}Create = ` + "`" + `INSERT INTO {{.TableName}} ({{.InsertCols}}) VALUES ({{.InsertPlaceholders}}) RETURNING *` + "`" + `
	sql{{.Name}}Update = ` + "`" + `UPDATE {{.TableName}} SET {{.UpdateSet}}, updated_at = NOW() WHERE id = ${{.UpdateIDIdx}} RETURNING *` + "`" + `
	sql{{.Name}}Delete = ` + "`" + `DELETE FROM {{.TableName}} WHERE id = $1` + "`" + `
)

func (s *{{.Name}}Store) Get(ctx context.Context, id string) (domain.{{.Name}}, error) {
	notFound := &domain.NotFoundError{Entity: "{{.Name}}", ID: id}
	v, err := queryOne[domain.{{.Name}}](ctx, s.pool, sql{{.Name}}Get, id)
	if err != nil {
		if errors.Is(err, pgx.ErrNoRows) {
			return domain.{{.Name}}{}, notFound
		}
		return domain.{{.Name}}{}, DecorateError(err, "{{.Name}}Store.Get")
	}
	return v, nil
}

func (s *{{.Name}}Store) List(ctx context.Context, limit, offset int) ([]domain.{{.Name}}, error) {
	return queryMany[domain.{{.Name}}](ctx, s.pool, sql{{.Name}}List, limit, offset)
}

func (s *{{.Name}}Store) Create(ctx context.Context, p domain.{{.Name}}) (domain.{{.Name}}, error) {
	const op = "{{.Name}}Store.Create"
	rows, err := s.pool.Query(ctx, sql{{.Name}}Create, {{.CreateArgs}})
	if err != nil {
		if IsUniqueViolation(err) {
			return domain.{{.Name}}{}, &domain.AlreadyExistsError{Entity: "{{.Name}}"}
		}
		return domain.{{.Name}}{}, DecorateError(err, op)
	}
	result, err := pgx.CollectOneRow(rows, pgx.RowToStructByName[domain.{{.Name}}])
	if err != nil {
		return domain.{{.Name}}{}, DecorateError(err, op)
	}
	return result, nil
}

func (s *{{.Name}}Store) Update(ctx context.Context, p domain.{{.Name}}) (domain.{{.Name}}, error) {
	const op = "{{.Name}}Store.Update"
	rows, err := s.pool.Query(ctx, sql{{.Name}}Update, {{.UpdateArgs}})
	if err != nil {
		if IsUniqueViolation(err) {
			return domain.{{.Name}}{}, &domain.AlreadyExistsError{Entity: "{{.Name}}"}
		}
		return domain.{{.Name}}{}, DecorateError(err, op)
	}
	result, err := pgx.CollectOneRow(rows, pgx.RowToStructByName[domain.{{.Name}}])
	if err != nil {
		if errors.Is(err, pgx.ErrNoRows) {
			return domain.{{.Name}}{}, &domain.NotFoundError{Entity: "{{.Name}}", ID: p.ID}
		}
		return domain.{{.Name}}{}, DecorateError(err, op)
	}
	return result, nil
}

func (s *{{.Name}}Store) Delete(ctx context.Context, id string) error {
	const op = "{{.Name}}Store.Delete"
	tag, err := s.pool.Exec(ctx, sql{{.Name}}Delete, id)
	if err != nil {
		return DecorateError(err, op)
	}
	if tag.RowsAffected() == 0 {
		return &domain.NotFoundError{Entity: "{{.Name}}", ID: id}
	}
	return nil
}
`

// registryTmplPostgres fully regenerates internal/app/registry.go for Postgres projects
const registryTmplPostgres = `// Code generated by scaffold. DO NOT EDIT.

package app

import (
	"log/slog"

	"github.com/jackc/pgx/v5/pgxpool"
{{- if .Models}}

	httpadapter "{{.ModulePath}}/internal/adapters/http"
	"{{.ModulePath}}/internal/adapters/store"
	"{{.ModulePath}}/internal/core/domain"
	"{{.ModulePath}}/internal/core/ports"
	"{{.ModulePath}}/internal/core/services"
{{- end}}
)

// Stores groups all database outbound adapters.
type Stores struct {
{{- range .Models}}
	{{.Name}} ports.{{.Name}}Store
{{- end}}
}

// Services groups all core business logic services.
type Services struct {
{{- range .Models}}
	{{.Name}} ports.{{.Name}}Service
{{- end}}
}

// Handlers groups all entry point HTTP controllers.
type Handlers struct {
{{- range .Models}}
	{{.Name}} *httpadapter.CRUDHandler[domain.{{.Name}}]
{{- end}}
}

// Registry is the unified Hexagonal container of the application.
type Registry struct {
	Stores   *Stores
	Services *Services
	Handlers *Handlers
}

// NewRegistry constructs and wires the entire dependency graph statically at startup.
func NewRegistry(pool *pgxpool.Pool, logger *slog.Logger) *Registry {
{{- if .Models}}
	st := store.NewStore(pool)
{{- end}}

	stores := &Stores{
{{- range .Models}}
		{{.Name}}: &store.{{.Name}}Store{Store: st},
{{- end}}
	}

	svcs := &Services{
{{- range .Models}}
		{{.Name}}: services.New{{.Name}}Service(stores.{{.Name}}, logger),
{{- end}}
	}

	handlers := &Handlers{
{{- range .Models}}
		{{.Name}}: httpadapter.NewCRUDHandler(svcs.{{.Name}}, "{{.Name}}", "", logger),
{{- end}}
	}

	return &Registry{
		Stores:   stores,
		Services: svcs,
		Handlers: handlers,
	}
}
`

// schemaTmplPostgres generates the SQL block inserted into schema.sql for Postgres
const schemaTmplPostgres = `-- scaffold:table:{{.Name}}:start
CREATE TABLE IF NOT EXISTS {{.TableName}} (
    id UUID PRIMARY KEY DEFAULT uuidv7(),
{{- range .Fields}}
    {{.Name}} {{.SQLType}}{{if .NotNull}} NOT NULL{{end}}{{.SQLModifiers}},
{{- end}}
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
{{range .Fields}}{{if .HasIndex}}
CREATE INDEX{{if .IsJSON}} idx_{{$.TableName}}_{{.Name}} ON {{$.TableName}} USING GIN ({{.Name}});
{{- else}} idx_{{$.TableName}}_{{.Name}} ON {{$.TableName}}({{.Name}});
{{- end}}{{end}}{{end}}
CREATE OR REPLACE FUNCTION trg_set_updated_at()
RETURNS trigger LANGUAGE plpgsql AS $$
BEGIN NEW.updated_at = NOW(); RETURN NEW; END;
$$;

CREATE TRIGGER trg_{{.TableName}}_updated_at
    BEFORE UPDATE ON {{.TableName}}
    FOR EACH ROW EXECUTE FUNCTION trg_set_updated_at();
-- scaffold:table:{{.Name}}:end`

// migrationCreateTmplPostgres generates the initial CREATE TABLE migration for Postgres (goose format)
const migrationCreateTmplPostgres = `-- +goose Up
CREATE TABLE IF NOT EXISTS {{.TableName}} (
    id UUID PRIMARY KEY DEFAULT uuidv7(),
{{- range .Fields}}
    {{.Name}} {{.SQLType}}{{if .NotNull}} NOT NULL{{end}}{{.SQLModifiers}},
{{- end}}
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
{{range .Fields}}{{if .HasIndex}}
CREATE INDEX{{if .IsJSON}} idx_{{$.TableName}}_{{.Name}} ON {{$.TableName}} USING GIN ({{.Name}});
{{- else}} idx_{{$.TableName}}_{{.Name}} ON {{$.TableName}}({{.Name}});
{{- end}}{{end}}{{end}}
-- +goose StatementBegin
CREATE OR REPLACE FUNCTION trg_set_updated_at()
RETURNS trigger LANGUAGE plpgsql AS $$
BEGIN NEW.updated_at = NOW(); RETURN NEW; END;
$$;
-- +goose StatementEnd

CREATE TRIGGER trg_{{.TableName}}_updated_at
    BEFORE UPDATE ON {{.TableName}}
    FOR EACH ROW EXECUTE FUNCTION trg_set_updated_at();

-- +goose Down
DROP TRIGGER IF EXISTS trg_{{.TableName}}_updated_at ON {{.TableName}};
DROP TABLE IF EXISTS {{.TableName}};
`

// migrationDropTableTmplPostgres generates the DROP TABLE migration for destroy on Postgres
const migrationDropTableTmplPostgres = `-- +goose Up
DROP TRIGGER IF EXISTS trg_{{.TableName}}_updated_at ON {{.TableName}};
DROP TABLE IF EXISTS {{.TableName}};

-- +goose Down
CREATE TABLE IF NOT EXISTS {{.TableName}} (
    id UUID PRIMARY KEY DEFAULT uuidv7(),
{{- range .Fields}}
    {{.Name}} {{.SQLType}}{{if .NotNull}} NOT NULL{{end}}{{.SQLModifiers}},
{{- end}}
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
{{range .Fields}}{{if .HasIndex}}
CREATE INDEX{{if .IsJSON}} idx_{{$.TableName}}_{{.Name}} ON {{$.TableName}} USING GIN ({{.Name}});
{{- else}} idx_{{$.TableName}}_{{.Name}} ON {{$.TableName}}({{.Name}});
{{- end}}{{end}}{{end}}
-- +goose StatementBegin
CREATE OR REPLACE FUNCTION trg_set_updated_at()
RETURNS trigger LANGUAGE plpgsql AS $$
BEGIN NEW.updated_at = NOW(); RETURN NEW; END;
$$;
-- +goose StatementEnd

CREATE TRIGGER trg_{{.TableName}}_updated_at
    BEFORE UPDATE ON {{.TableName}}
    FOR EACH ROW EXECUTE FUNCTION trg_set_updated_at();
`

