package generator

// domainGenTmpl generates internal/core/domain/{model}_gen.go — the struct and
// identity methods. Fully regenerated; no markers.
const domainGenTmpl = `// Code generated by scaffold. DO NOT EDIT.

package domain
{{- if .NeedsTimeImport}}

import "time"
{{- end}}
{{- if .NeedsJSONImport}}

import "encoding/json"
{{- end}}

type {{.Name}} struct {
{{.FieldsBlock}}}

func ({{.Receiver}} {{.Name}}) GetID() string { return {{.Receiver}}.ID }

func ({{.Receiver}} {{.Name}}) WithID(id string) {{.Name}} { {{.Receiver}}.ID = id; return {{.Receiver}} }
`

// domainUserTmpl generates internal/core/domain/{model}.go — written once,
// never overwritten. Holds Validate() and any custom methods.
const domainUserTmpl = `package domain

// SAFE TO EDIT — scaffold writes this file once and never regenerates it.
// The struct, GetID and WithID live in the generated *_gen.go file.

// Validate enforces business rules on {{.Name}}. Add your rules and custom methods here.
func ({{.Receiver}} {{.Name}}) Validate() error {
	return nil
}
`

// portsTmpl generates internal/core/ports/{model}.go
const portsTmpl = `// Code generated by scaffold. DO NOT EDIT.

package ports

import "{{.ModulePath}}/internal/core/domain"

type {{.Name}}Store interface {
	CRUDStore[domain.{{.Name}}]
}

type {{.Name}}Service interface {
	CRUDService[domain.{{.Name}}]
}
`

// serviceGenTmpl generates internal/core/services/{model}_service_gen.go
const serviceGenTmpl = `// Code generated by scaffold. DO NOT EDIT.

package services

import (
	"context"
	"log/slog"

	"{{.ModulePath}}/internal/core/domain"
	"{{.ModulePath}}/internal/core/ports"
)

type {{.Name}}Service struct {
	store  ports.{{.Name}}Store
	logger *slog.Logger
}

func New{{.Name}}Service(store ports.{{.Name}}Store, logger *slog.Logger) *{{.Name}}Service {
	return &{{.Name}}Service{store: store, logger: logger}
}

func (s *{{.Name}}Service) Get(ctx context.Context, id string) (*domain.{{.Name}}, error) {
	s.logger.DebugContext(ctx, "fetching {{.Lower}}", "id", id)
	v, err := s.store.Get(ctx, id)
	if err != nil {
		return nil, err
	}
	return &v, nil
}

func (s *{{.Name}}Service) List(ctx context.Context, limit, offset int) ([]domain.{{.Name}}, error) {
	s.logger.DebugContext(ctx, "listing {{.Lower}}s", "limit", limit, "offset", offset)
	return s.store.List(ctx, limit, offset)
}

func (s *{{.Name}}Service) Create(ctx context.Context, p domain.{{.Name}}) (*domain.{{.Name}}, error) {
	s.logger.DebugContext(ctx, "creating {{.Lower}}")
	if err := p.Validate(); err != nil {
		return nil, err
	}
	v, err := s.store.Create(ctx, p)
	if err != nil {
		return nil, err
	}
	return &v, nil
}

func (s *{{.Name}}Service) Update(ctx context.Context, p domain.{{.Name}}) (*domain.{{.Name}}, error) {
	s.logger.DebugContext(ctx, "updating {{.Lower}}", "id", p.ID)
	if err := p.Validate(); err != nil {
		return nil, err
	}
	v, err := s.store.Update(ctx, p)
	if err != nil {
		return nil, err
	}
	return &v, nil
}

func (s *{{.Name}}Service) Delete(ctx context.Context, id string) error {
	s.logger.DebugContext(ctx, "deleting {{.Lower}}", "id", id)
	return s.store.Delete(ctx, id)
}
`

// serviceUserTmpl generates internal/core/services/{model}_service.go (created once)
const serviceUserTmpl = `package services

// SAFE TO EDIT — scaffold writes this file once and never regenerates it.
// {{.Name}}Service custom business logic goes here.
`

// storeGenTmpl generates internal/adapters/store/{model}_store_gen.go
const storeGenTmpl = `// Code generated by scaffold. DO NOT EDIT.

package store

import (
	"context"
	"database/sql"
	"errors"
{{- if .NeedsJSON}}
	"encoding/json"
{{- end}}

	"{{.ModulePath}}/internal/core/domain"
	"{{.ModulePath}}/internal/core/ports"
)

// {{.Name}}Store implements ports.CRUDStore[domain.{{.Name}}].
type {{.Name}}Store struct{ *Store }

var _ ports.CRUDStore[domain.{{.Name}}] = (*{{.Name}}Store)(nil)

const (
	sql{{.Name}}Get    = ` + "`" + `SELECT {{.SelectCols}} FROM {{.TableName}} WHERE id = ?{{if .SoftDelete}} AND deleted_at IS NULL{{end}}` + "`" + `
	// id is a UUIDv7 (time-ordered), so ORDER BY id DESC returns newest first
	// with a deterministic order — required for stable pagination.
	sql{{.Name}}List   = ` + "`" + `SELECT {{.SelectCols}} FROM {{.TableName}} {{if .SoftDelete}}WHERE deleted_at IS NULL {{end}}ORDER BY id DESC LIMIT ? OFFSET ?` + "`" + `
	sql{{.Name}}Create = ` + "`" + `INSERT INTO {{.TableName}} ({{.InsertCols}}) VALUES ({{.InsertPlaceholders}}) RETURNING id, created_at, updated_at` + "`" + `
	sql{{.Name}}Update = ` + "`" + `UPDATE {{.TableName}} SET {{.UpdateSet}}, updated_at = CURRENT_TIMESTAMP WHERE id = ?{{if .SoftDelete}} AND deleted_at IS NULL{{end}} RETURNING created_at, updated_at` + "`" + `
	sql{{.Name}}Delete = ` + "`" + `{{if .SoftDelete}}UPDATE {{.TableName}} SET deleted_at = CURRENT_TIMESTAMP WHERE id = ? AND deleted_at IS NULL{{else}}DELETE FROM {{.TableName}} WHERE id = ?{{end}}` + "`" + `
)

{{template "scanFunc" .}}

func (s *{{.Name}}Store) Get(ctx context.Context, id string) (domain.{{.Name}}, error) {
	const op = "{{.Name}}Store.Get"
	row := s.db.QueryRowContext(ctx, sql{{.Name}}Get, id)
	notFoundErr := &domain.NotFoundError{Entity: "{{.Name}}", ID: id}
	return queryRow(row, notFoundErr, op, func(r *sql.Row) (domain.{{.Name}}, error) {
		return scan{{.Name}}(r)
	})
}

func (s *{{.Name}}Store) List(ctx context.Context, limit, offset int) ([]domain.{{.Name}}, error) {
	const op = "{{.Name}}Store.List"
	rows, err := s.db.QueryContext(ctx, sql{{.Name}}List, limit, offset)
	if err != nil {
		return nil, DecorateError(err, op)
	}
	return collectRows(rows, op, func(r *sql.Rows) (domain.{{.Name}}, error) {
		return scan{{.Name}}Rows(r)
	})
}

func (s *{{.Name}}Store) Create(ctx context.Context, p domain.{{.Name}}) (domain.{{.Name}}, error) {
	const op = "{{.Name}}Store.Create"
	row := s.db.QueryRowContext(ctx, sql{{.Name}}Create, {{.CreateArgs}})
	if err := row.Scan(&p.ID, &p.CreatedAt, &p.UpdatedAt); err != nil {
		if IsUniqueViolation(err) {
			return domain.{{.Name}}{}, &domain.AlreadyExistsError{Entity: "{{.Name}}"}
		}
		return domain.{{.Name}}{}, DecorateError(err, op)
	}
	return p, nil
}

func (s *{{.Name}}Store) Update(ctx context.Context, p domain.{{.Name}}) (domain.{{.Name}}, error) {
	const op = "{{.Name}}Store.Update"
	row := s.db.QueryRowContext(ctx, sql{{.Name}}Update, {{.UpdateArgs}})
	if err := row.Scan(&p.CreatedAt, &p.UpdatedAt); err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return domain.{{.Name}}{}, &domain.NotFoundError{Entity: "{{.Name}}", ID: p.ID}
		}
		if IsUniqueViolation(err) {
			return domain.{{.Name}}{}, &domain.AlreadyExistsError{Entity: "{{.Name}}"}
		}
		return domain.{{.Name}}{}, DecorateError(err, op)
	}
	return p, nil
}

func (s *{{.Name}}Store) Delete(ctx context.Context, id string) error {
	const op = "{{.Name}}Store.Delete"
	res, err := s.db.ExecContext(ctx, sql{{.Name}}Delete, id)
	if err != nil {
		return DecorateError(err, op)
	}
	n, err := res.RowsAffected()
	if err != nil {
		return DecorateError(err, op)
	}
	if n == 0 {
		return &domain.NotFoundError{Entity: "{{.Name}}", ID: id}
	}
	return nil
}
`

// scanFuncTmpl is a sub-template rendered inside storeGenTmpl.
// Handles regular fields and json.RawMessage two-step scanning.
const scanFuncTmpl = `{{define "scanFunc"}}
func scan{{.Name}}(r *sql.Row) (domain.{{.Name}}, error) {
	var p domain.{{.Name}}
{{- range .Fields}}{{if or .IsJSON .IsArray}}
	var {{.GoName}}Bytes []byte
{{- end}}{{end}}
	err := r.Scan({{.ScanArgs}})
	if err != nil {
		return domain.{{.Name}}{}, err
	}
{{- range .Fields}}{{if .IsJSON}}
	if {{.GoName}}Bytes != nil {
		p.{{.GoName}} = json.RawMessage({{.GoName}}Bytes)
	}
{{- else if .IsArray}}
	if {{.GoName}}Bytes != nil {
		if err := json.Unmarshal({{.GoName}}Bytes, &p.{{.GoName}}); err != nil {
			return domain.{{$.Name}}{}, err
		}
	}
{{- end}}{{end}}
	return p, nil
}

func scan{{.Name}}Rows(r *sql.Rows) (domain.{{.Name}}, error) {
	var p domain.{{.Name}}
{{- range .Fields}}{{if or .IsJSON .IsArray}}
	var {{.GoName}}Bytes []byte
{{- end}}{{end}}
	err := r.Scan({{.ScanArgs}})
	if err != nil {
		return domain.{{.Name}}{}, err
	}
{{- range .Fields}}{{if .IsJSON}}
	if {{.GoName}}Bytes != nil {
		p.{{.GoName}} = json.RawMessage({{.GoName}}Bytes)
	}
{{- else if .IsArray}}
	if {{.GoName}}Bytes != nil {
		if err := json.Unmarshal({{.GoName}}Bytes, &p.{{.GoName}}); err != nil {
			return domain.{{$.Name}}{}, err
		}
	}
{{- end}}{{end}}
	return p, nil
}
{{end}}`

// storeUserTmpl generates internal/adapters/store/{model}_store.go (created once)
const storeUserTmpl = `package store

// SAFE TO EDIT — scaffold writes this file once and never regenerates it.
// {{.Name}} custom store queries go here.

// Example:
// func (s *{{.Name}}Store) CustomMethod(ctx context.Context) ([]domain.{{.Name}}, error) {
// 	return nil, nil
// }
`

// schemaTmpl generates the SQL block inserted into schema.sql
const schemaTmpl = `-- scaffold:table:{{.Name}}:start
CREATE TABLE IF NOT EXISTS {{.TableName}} (
    {{.IDDef}},
{{- range .Fields}}
    {{.Name}} {{.SQLType}}{{if .NotNull}} NOT NULL{{end}}{{.SQLModifiers}},
{{- end}}
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP{{if .SoftDelete}},
    deleted_at DATETIME{{end}}
);
{{- range .Fields}}{{if .HasIndex}}
CREATE INDEX IF NOT EXISTS idx_{{$.TableName}}_{{.Name}} ON {{$.TableName}}({{.Name}});
{{- end}}{{end}}
{{- range .UniqueTogether}}
CREATE UNIQUE INDEX IF NOT EXISTS {{.Name}} ON {{$.TableName}}({{.ColsCS}});
{{- end}}

CREATE TRIGGER IF NOT EXISTS trg_{{.TableName}}_updated_at
AFTER UPDATE ON {{.TableName}}
FOR EACH ROW
WHEN NEW.updated_at <= OLD.updated_at
BEGIN
    UPDATE {{.TableName}} SET updated_at = CURRENT_TIMESTAMP WHERE id = OLD.id;
END;
-- scaffold:table:{{.Name}}:end`

// migrationCreateTmpl generates the initial CREATE TABLE migration (goose format)
const migrationCreateTmpl = `-- +goose Up
CREATE TABLE IF NOT EXISTS {{.TableName}} (
    {{.IDDef}},
{{- range .Fields}}
    {{.Name}} {{.SQLType}}{{if .NotNull}} NOT NULL{{end}}{{.SQLModifiers}},
{{- end}}
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP{{if .SoftDelete}},
    deleted_at DATETIME{{end}}
);
{{- range .Fields}}{{if .HasIndex}}
CREATE INDEX IF NOT EXISTS idx_{{$.TableName}}_{{.Name}} ON {{$.TableName}}({{.Name}});
{{- end}}{{end}}
{{- range .UniqueTogether}}
CREATE UNIQUE INDEX IF NOT EXISTS {{.Name}} ON {{$.TableName}}({{.ColsCS}});
{{- end}}

-- +goose StatementBegin
CREATE TRIGGER IF NOT EXISTS trg_{{.TableName}}_updated_at
AFTER UPDATE ON {{.TableName}}
FOR EACH ROW
WHEN NEW.updated_at <= OLD.updated_at
BEGIN
    UPDATE {{.TableName}} SET updated_at = CURRENT_TIMESTAMP WHERE id = OLD.id;
END;
-- +goose StatementEnd

-- +goose Down
{{- range .UniqueTogether}}
DROP INDEX IF EXISTS {{.Name}};
{{- end}}
DROP TRIGGER IF EXISTS trg_{{.TableName}}_updated_at;
DROP TABLE IF EXISTS {{.TableName}};
`

// migrationAddColTmpl generates ALTER TABLE ADD COLUMN migration.
// NOT NULL columns without an explicit default get a zero-value DEFAULT
// (SQLite rejects ADD COLUMN NOT NULL without one; Postgres rejects it on
// non-empty tables). On SQLite, unique columns get a CREATE UNIQUE INDEX
// instead of inline UNIQUE, which ADD COLUMN does not support.
const migrationAddColTmpl = `-- +goose Up
{{- range .Added}}
ALTER TABLE {{$.TableName}} ADD COLUMN {{.Name}} {{.SQLType}}{{if .NotNull}} NOT NULL{{end}}{{.SQLModifiers}};
{{- end}}
{{- range .Added}}{{if .HasUnique}}
CREATE UNIQUE INDEX IF NOT EXISTS idx_{{$.TableName}}_{{.Name}}_unique ON {{$.TableName}}({{.Name}});
{{- end}}{{end}}
{{- range .Added}}{{if .HasIndex}}
CREATE INDEX IF NOT EXISTS idx_{{$.TableName}}_{{.Name}} ON {{$.TableName}}{{if and $.IsPostgres (or .IsJSON .IsArray)}} USING GIN ({{.Name}}){{else}}({{.Name}}){{end}};
{{- end}}{{end}}

-- +goose Down
{{- range .Added}}{{if .HasIndex}}
DROP INDEX IF EXISTS idx_{{$.TableName}}_{{.Name}};
{{- end}}{{end}}
{{- range .Added}}{{if .HasUnique}}
DROP INDEX IF EXISTS idx_{{$.TableName}}_{{.Name}}_unique;
{{- end}}{{end}}
{{- range .Added}}
ALTER TABLE {{$.TableName}} DROP COLUMN {{.Name}};
{{- end}}
`

// migrationDropColTmpl generates ALTER TABLE DROP COLUMN migration. Indexes on
// the column are dropped first: SQLite refuses to drop an indexed column, and
// on Postgres the statements are harmless no-ops if the index is already gone.
const migrationDropColTmpl = `-- +goose Up
{{- range .Removed}}{{if .HasIndex}}
DROP INDEX IF EXISTS idx_{{$.TableName}}_{{.Name}};
{{- end}}{{end}}
{{- range .Removed}}{{if .HasUnique}}
DROP INDEX IF EXISTS idx_{{$.TableName}}_{{.Name}}_unique;
{{- end}}{{end}}
{{- range .Removed}}
ALTER TABLE {{$.TableName}} DROP COLUMN {{.Name}};
{{- end}}

-- +goose Down
{{- range .Removed}}
ALTER TABLE {{$.TableName}} ADD COLUMN {{.Name}} {{.SQLType}}{{if .NotNull}} NOT NULL{{end}}{{.SQLModifiers}};
{{- end}}
{{- range .Removed}}{{if .HasUnique}}
CREATE UNIQUE INDEX IF NOT EXISTS idx_{{$.TableName}}_{{.Name}}_unique ON {{$.TableName}}({{.Name}});
{{- end}}{{end}}
{{- range .Removed}}{{if .HasIndex}}
CREATE INDEX IF NOT EXISTS idx_{{$.TableName}}_{{.Name}} ON {{$.TableName}}{{if and $.IsPostgres (or .IsJSON .IsArray)}} USING GIN ({{.Name}}){{else}}({{.Name}}){{end}};
{{- end}}{{end}}
`

// migrationDropTableTmpl generates the DROP TABLE migration for destroy
const migrationDropTableTmpl = `-- +goose Up
DROP TRIGGER IF EXISTS trg_{{.TableName}}_updated_at;
DROP TABLE IF EXISTS {{.TableName}};

-- +goose Down
CREATE TABLE IF NOT EXISTS {{.TableName}} (
    {{.IDDef}},
{{- range .Fields}}
    {{.Name}} {{.SQLType}}{{if .NotNull}} NOT NULL{{end}}{{.SQLModifiers}},
{{- end}}
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);
{{- range .Fields}}{{if .HasIndex}}
CREATE INDEX IF NOT EXISTS idx_{{$.TableName}}_{{.Name}} ON {{$.TableName}}({{.Name}});
{{- end}}{{end}}
`

// routesGenTmpl generates internal/app/routes_gen.go — model HTTP (and gRPC)
// registrations. Replaces the old scaffold:routes/scaffold:grpc marker blocks in
// app.go; app.go now just calls a.registerGeneratedRoutes(r) (and, in gRPC mode,
// a.registerGeneratedGRPC()).
const routesGenTmpl = `// Code generated by scaffold. DO NOT EDIT.

package app

import "github.com/go-chi/chi/v5"

// registerGeneratedRoutes mounts all model HTTP routes onto r.
func (a *App) registerGeneratedRoutes(r chi.Router) {
{{- range .Models}}
{{- if not .NoHandler}}
{{- if $.IsSSR}}
	r.Mount(a.registry.Handlers.{{.Name}}.Prefix(), a.registry.Handlers.{{.Name}}.Router())
{{- else}}
	r.Route(a.registry.Handlers.{{.Name}}.Prefix(), a.registry.Handlers.{{.Name}}.RegisterRoutes)
{{- end}}
{{- end}}
{{- end}}
}
{{- if .GRPC}}

// registerGeneratedGRPC registers all model gRPC servers on a.grpcServer.
func (a *App) registerGeneratedGRPC() {
{{- range .Models}}
{{- if not .NoHandler}}
	a.registry.GRPCHandlers.{{.Name}}.Register(a.grpcServer)
{{- end}}
{{- end}}
}
{{- end}}
`

// registryTmpl fully regenerates internal/app/registry.go from the manifest
const registryTmpl = `// Code generated by scaffold. DO NOT EDIT.

package app

import (
	"database/sql"
	"log/slog"
{{- if .Models}}

	{{- if .HasHandlers}}
	httpadapter "{{.ModulePath}}/internal/adapters/http"
	{{- end}}
	{{- if and .GRPC .HasHandlers}}
	grpcadapter "{{.ModulePath}}/internal/adapters/grpc"
	{{- end}}
	"{{.ModulePath}}/internal/adapters/store"
	{{- if .HasHandlers}}
	"{{.ModulePath}}/internal/core/domain"
	{{- end}}
	"{{.ModulePath}}/internal/core/ports"
	"{{.ModulePath}}/internal/core/services"
{{- end}}
)

// Stores groups all database outbound adapters.
type Stores struct {
{{- range .Models}}
	{{.Name}} ports.{{.Name}}Store
{{- end}}
}

// Services groups all core business logic services.
type Services struct {
{{- range .Models}}
	{{.Name}} ports.{{.Name}}Service
{{- end}}
}

// Handlers groups all entry point HTTP controllers.
type Handlers struct {
{{- range .Models}}
{{- if not .NoHandler}}
	{{.Name}} *httpadapter.CRUDHandler[domain.{{.Name}}]
{{- end}}
{{- end}}
}

{{- if .GRPC}}

// GRPCHandlers groups all gRPC server handlers.
type GRPCHandlers struct {
{{- range .Models}}
{{- if not .NoHandler}}
	{{.Name}} *grpcadapter.{{.Name}}Handler
{{- end}}
{{- end}}
}
{{- end}}

// Registry is the unified Hexagonal container of the application.
type Registry struct {
	Stores   *Stores
	Services *Services
	Handlers *Handlers
	{{- if .GRPC}}
	GRPCHandlers *GRPCHandlers
	{{- end}}
}

// NewRegistry constructs and wires the entire dependency graph statically at startup.
func NewRegistry(db *sql.DB, logger *slog.Logger) *Registry {
{{- if .Models}}
	st := store.NewStore(db)
{{- end}}

	stores := &Stores{
{{- range .Models}}
		{{.Name}}: &store.{{.Name}}Store{Store: st},
{{- end}}
	}

	svcs := &Services{
{{- range .Models}}
		{{.Name}}: services.New{{.Name}}Service(stores.{{.Name}}, logger),
{{- end}}
	}

	handlers := &Handlers{
{{- range .Models}}
{{- if not .NoHandler}}
		{{.Name}}: httpadapter.NewCRUDHandler(svcs.{{.Name}}, "{{.Name}}", "", httpadapter.CRUDOps{List: {{.Ops.List}}, Read: {{.Ops.Read}}, Create: {{.Ops.Create}}, Update: {{.Ops.Update}}, Delete: {{.Ops.Delete}}}, logger),
{{- end}}
{{- end}}
	}

	{{- if .GRPC}}
	grpcHandlers := &GRPCHandlers{
{{- range .Models}}
{{- if not .NoHandler}}
		{{.Name}}: grpcadapter.New{{.Name}}Handler(svcs.{{.Name}}),
{{- end}}
{{- end}}
	}
	{{- end}}

	return &Registry{
		Stores:   stores,
		Services: svcs,
		Handlers: handlers,
		{{- if .GRPC}}
		GRPCHandlers: grpcHandlers,
		{{- end}}
	}
}
`

// storeGenTmplPostgres generates internal/adapters/store/{model}_store_gen.go for Postgres
const storeGenTmplPostgres = `// Code generated by scaffold. DO NOT EDIT.

package store

import (
	"context"
	"errors"

	"github.com/jackc/pgx/v5"
	"{{.ModulePath}}/internal/core/domain"
	"{{.ModulePath}}/internal/core/ports"
)

// {{.Name}}Store implements ports.CRUDStore[domain.{{.Name}}].
type {{.Name}}Store struct{ *Store }

var _ ports.CRUDStore[domain.{{.Name}}] = (*{{.Name}}Store)(nil)

const (
	sql{{.Name}}Get    = ` + "`" + `SELECT {{.SelectCols}} FROM {{.TableName}} WHERE id = $1{{if .SoftDelete}} AND deleted_at IS NULL{{end}}` + "`" + `
	// id is a UUIDv7 (time-ordered), so ORDER BY id DESC returns newest first
	// with a deterministic order — required for stable pagination.
	sql{{.Name}}List   = ` + "`" + `SELECT {{.SelectCols}} FROM {{.TableName}} {{if .SoftDelete}}WHERE deleted_at IS NULL {{end}}ORDER BY id DESC LIMIT $1 OFFSET $2` + "`" + `
	sql{{.Name}}Create = ` + "`" + `INSERT INTO {{.TableName}} ({{.InsertCols}}) VALUES ({{.InsertPlaceholders}}) RETURNING {{.SelectCols}}` + "`" + `
	sql{{.Name}}Update = ` + "`" + `UPDATE {{.TableName}} SET {{.UpdateSet}}, updated_at = NOW() WHERE id = ${{.UpdateIDIdx}}{{if .SoftDelete}} AND deleted_at IS NULL{{end}} RETURNING {{.SelectCols}}` + "`" + `
	sql{{.Name}}Delete = ` + "`" + `{{if .SoftDelete}}UPDATE {{.TableName}} SET deleted_at = NOW() WHERE id = $1 AND deleted_at IS NULL{{else}}DELETE FROM {{.TableName}} WHERE id = $1{{end}}` + "`" + `
)

func (s *{{.Name}}Store) Get(ctx context.Context, id string) (domain.{{.Name}}, error) {
	notFound := &domain.NotFoundError{Entity: "{{.Name}}", ID: id}
	v, err := queryOne[domain.{{.Name}}](ctx, s.pool, sql{{.Name}}Get, id)
	if err != nil {
		if errors.Is(err, pgx.ErrNoRows) {
			return domain.{{.Name}}{}, notFound
		}
		return domain.{{.Name}}{}, DecorateError(err, "{{.Name}}Store.Get")
	}
	return v, nil
}

func (s *{{.Name}}Store) List(ctx context.Context, limit, offset int) ([]domain.{{.Name}}, error) {
	return queryMany[domain.{{.Name}}](ctx, s.pool, sql{{.Name}}List, limit, offset)
}

func (s *{{.Name}}Store) Create(ctx context.Context, p domain.{{.Name}}) (domain.{{.Name}}, error) {
	const op = "{{.Name}}Store.Create"
	rows, err := s.pool.Query(ctx, sql{{.Name}}Create, {{.CreateArgs}})
	if err != nil {
		return domain.{{.Name}}{}, DecorateError(err, op)
	}
	// pgx defers query execution errors to row collection, so constraint
	// violations surface here — not at Query time.
	result, err := pgx.CollectOneRow(rows, pgx.RowToStructByName[domain.{{.Name}}])
	if err != nil {
		if IsUniqueViolation(err) {
			return domain.{{.Name}}{}, &domain.AlreadyExistsError{Entity: "{{.Name}}"}
		}
		return domain.{{.Name}}{}, DecorateError(err, op)
	}
	return result, nil
}

func (s *{{.Name}}Store) Update(ctx context.Context, p domain.{{.Name}}) (domain.{{.Name}}, error) {
	const op = "{{.Name}}Store.Update"
	rows, err := s.pool.Query(ctx, sql{{.Name}}Update, {{.UpdateArgs}})
	if err != nil {
		return domain.{{.Name}}{}, DecorateError(err, op)
	}
	// pgx defers query execution errors to row collection, so constraint
	// violations surface here — not at Query time.
	result, err := pgx.CollectOneRow(rows, pgx.RowToStructByName[domain.{{.Name}}])
	if err != nil {
		if errors.Is(err, pgx.ErrNoRows) {
			return domain.{{.Name}}{}, &domain.NotFoundError{Entity: "{{.Name}}", ID: p.ID}
		}
		if IsUniqueViolation(err) {
			return domain.{{.Name}}{}, &domain.AlreadyExistsError{Entity: "{{.Name}}"}
		}
		return domain.{{.Name}}{}, DecorateError(err, op)
	}
	return result, nil
}

func (s *{{.Name}}Store) Delete(ctx context.Context, id string) error {
	const op = "{{.Name}}Store.Delete"
	tag, err := s.pool.Exec(ctx, sql{{.Name}}Delete, id)
	if err != nil {
		return DecorateError(err, op)
	}
	if tag.RowsAffected() == 0 {
		return &domain.NotFoundError{Entity: "{{.Name}}", ID: id}
	}
	return nil
}
`

// registryTmplPostgres fully regenerates internal/app/registry.go for Postgres projects
const registryTmplPostgres = `// Code generated by scaffold. DO NOT EDIT.

package app

import (
	"log/slog"

	"github.com/jackc/pgx/v5/pgxpool"
{{- if .Models}}

	{{- if .HasHandlers}}
	httpadapter "{{.ModulePath}}/internal/adapters/http"
	{{- end}}
	{{- if and .GRPC .HasHandlers}}
	grpcadapter "{{.ModulePath}}/internal/adapters/grpc"
	{{- end}}
	"{{.ModulePath}}/internal/adapters/store"
	{{- if .HasHandlers}}
	"{{.ModulePath}}/internal/core/domain"
	{{- end}}
	"{{.ModulePath}}/internal/core/ports"
	"{{.ModulePath}}/internal/core/services"
{{- end}}
)

// Stores groups all database outbound adapters.
type Stores struct {
{{- range .Models}}
	{{.Name}} ports.{{.Name}}Store
{{- end}}
}

// Services groups all core business logic services.
type Services struct {
{{- range .Models}}
	{{.Name}} ports.{{.Name}}Service
{{- end}}
}

// Handlers groups all entry point HTTP controllers.
type Handlers struct {
{{- range .Models}}
{{- if not .NoHandler}}
	{{.Name}} *httpadapter.CRUDHandler[domain.{{.Name}}]
{{- end}}
{{- end}}
}

{{- if .GRPC}}

// GRPCHandlers groups all gRPC server handlers.
type GRPCHandlers struct {
{{- range .Models}}
{{- if not .NoHandler}}
	{{.Name}} *grpcadapter.{{.Name}}Handler
{{- end}}
{{- end}}
}
{{- end}}

// Registry is the unified Hexagonal container of the application.
type Registry struct {
	Stores   *Stores
	Services *Services
	Handlers *Handlers
	{{- if .GRPC}}
	GRPCHandlers *GRPCHandlers
	{{- end}}
}

// NewRegistry constructs and wires the entire dependency graph statically at startup.
func NewRegistry(pool *pgxpool.Pool, logger *slog.Logger) *Registry {
{{- if .Models}}
	st := store.NewStore(pool)
{{- end}}

	stores := &Stores{
{{- range .Models}}
		{{.Name}}: &store.{{.Name}}Store{Store: st},
{{- end}}
	}

	svcs := &Services{
{{- range .Models}}
		{{.Name}}: services.New{{.Name}}Service(stores.{{.Name}}, logger),
{{- end}}
	}

	handlers := &Handlers{
{{- range .Models}}
{{- if not .NoHandler}}
		{{.Name}}: httpadapter.NewCRUDHandler(svcs.{{.Name}}, "{{.Name}}", "", httpadapter.CRUDOps{List: {{.Ops.List}}, Read: {{.Ops.Read}}, Create: {{.Ops.Create}}, Update: {{.Ops.Update}}, Delete: {{.Ops.Delete}}}, logger),
{{- end}}
{{- end}}
	}

	{{- if .GRPC}}
	grpcHandlers := &GRPCHandlers{
{{- range .Models}}
{{- if not .NoHandler}}
		{{.Name}}: grpcadapter.New{{.Name}}Handler(svcs.{{.Name}}),
{{- end}}
{{- end}}
	}
	{{- end}}

	return &Registry{
		Stores:   stores,
		Services: svcs,
		Handlers: handlers,
		{{- if .GRPC}}
		GRPCHandlers: grpcHandlers,
		{{- end}}
	}
}
`

// schemaTmplPostgres generates the SQL block inserted into schema.sql for Postgres
const schemaTmplPostgres = `-- scaffold:table:{{.Name}}:start
CREATE TABLE IF NOT EXISTS {{.TableName}} (
    id UUID PRIMARY KEY DEFAULT uuidv7(),
{{- range .Fields}}
    {{.Name}} {{.SQLType}}{{if .NotNull}} NOT NULL{{end}}{{.SQLModifiers}},
{{- end}}
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(){{if .SoftDelete}},
    deleted_at TIMESTAMPTZ{{end}}
);
{{range .Fields}}{{if .HasIndex}}
CREATE INDEX{{if or .IsJSON .IsArray}} idx_{{$.TableName}}_{{.Name}} ON {{$.TableName}} USING GIN ({{.Name}});
{{- else}} idx_{{$.TableName}}_{{.Name}} ON {{$.TableName}}({{.Name}});
{{- end}}{{end}}{{end}}
{{- range .UniqueTogether}}
CREATE UNIQUE INDEX IF NOT EXISTS {{.Name}} ON {{$.TableName}}({{.ColsCS}});
{{- end}}
CREATE OR REPLACE FUNCTION trg_set_updated_at()
RETURNS trigger LANGUAGE plpgsql AS $$
BEGIN NEW.updated_at = NOW(); RETURN NEW; END;
$$;

CREATE TRIGGER trg_{{.TableName}}_updated_at
    BEFORE UPDATE ON {{.TableName}}
    FOR EACH ROW EXECUTE FUNCTION trg_set_updated_at();
-- scaffold:table:{{.Name}}:end`

// migrationCreateTmplPostgres generates the initial CREATE TABLE migration for Postgres (goose format)
const migrationCreateTmplPostgres = `-- +goose Up
CREATE TABLE IF NOT EXISTS {{.TableName}} (
    id UUID PRIMARY KEY DEFAULT uuidv7(),
{{- range .Fields}}
    {{.Name}} {{.SQLType}}{{if .NotNull}} NOT NULL{{end}}{{.SQLModifiers}},
{{- end}}
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(){{if .SoftDelete}},
    deleted_at TIMESTAMPTZ{{end}}
);
{{range .Fields}}{{if .HasIndex}}
CREATE INDEX{{if or .IsJSON .IsArray}} idx_{{$.TableName}}_{{.Name}} ON {{$.TableName}} USING GIN ({{.Name}});
{{- else}} idx_{{$.TableName}}_{{.Name}} ON {{$.TableName}}({{.Name}});
{{- end}}{{end}}{{end}}
{{- range .UniqueTogether}}
CREATE UNIQUE INDEX IF NOT EXISTS {{.Name}} ON {{$.TableName}}({{.ColsCS}});
{{- end}}
-- +goose StatementBegin
CREATE OR REPLACE FUNCTION trg_set_updated_at()
RETURNS trigger LANGUAGE plpgsql AS $$
BEGIN NEW.updated_at = NOW(); RETURN NEW; END;
$$;
-- +goose StatementEnd

CREATE TRIGGER trg_{{.TableName}}_updated_at
    BEFORE UPDATE ON {{.TableName}}
    FOR EACH ROW EXECUTE FUNCTION trg_set_updated_at();

-- +goose Down
{{- range .UniqueTogether}}
DROP INDEX IF EXISTS {{.Name}};
{{- end}}
DROP TRIGGER IF EXISTS trg_{{.TableName}}_updated_at ON {{.TableName}};
DROP TABLE IF EXISTS {{.TableName}};
`

// migrationDropTableTmplPostgres generates the DROP TABLE migration for destroy on Postgres
const migrationDropTableTmplPostgres = `-- +goose Up
DROP TRIGGER IF EXISTS trg_{{.TableName}}_updated_at ON {{.TableName}};
DROP TABLE IF EXISTS {{.TableName}};

-- +goose Down
CREATE TABLE IF NOT EXISTS {{.TableName}} (
    id UUID PRIMARY KEY DEFAULT uuidv7(),
{{- range .Fields}}
    {{.Name}} {{.SQLType}}{{if .NotNull}} NOT NULL{{end}}{{.SQLModifiers}},
{{- end}}
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
{{range .Fields}}{{if .HasIndex}}
CREATE INDEX{{if or .IsJSON .IsArray}} idx_{{$.TableName}}_{{.Name}} ON {{$.TableName}} USING GIN ({{.Name}});
{{- else}} idx_{{$.TableName}}_{{.Name}} ON {{$.TableName}}({{.Name}});
{{- end}}{{end}}{{end}}
-- +goose StatementBegin
CREATE OR REPLACE FUNCTION trg_set_updated_at()
RETURNS trigger LANGUAGE plpgsql AS $$
BEGIN NEW.updated_at = NOW(); RETURN NEW; END;
$$;
-- +goose StatementEnd

CREATE TRIGGER trg_{{.TableName}}_updated_at
    BEFORE UPDATE ON {{.TableName}}
    FOR EACH ROW EXECUTE FUNCTION trg_set_updated_at();
`

// protoTmpl generates api/proto/v1/{model}.proto
const protoTmpl = `syntax = "proto3";

package api.v1;

option go_package = "{{.ModulePath}}/internal/adapters/grpc/pb";

import "google/protobuf/timestamp.proto";

service {{.Name}}Service {
  {{- if .Ops.Create}}
  rpc Create{{.Name}} (Create{{.Name}}Request) returns ({{.Name}}Response);
  {{- end}}
  {{- if .Ops.Read}}
  rpc Get{{.Name}}    (Get{{.Name}}Request)    returns ({{.Name}}Response);
  {{- end}}
  {{- if .Ops.Update}}
  rpc Update{{.Name}} (Update{{.Name}}Request) returns ({{.Name}}Response);
  {{- end}}
  {{- if .Ops.Delete}}
  rpc Delete{{.Name}} (Delete{{.Name}}Request) returns (Delete{{.Name}}Response);
  {{- end}}
  {{- if .Ops.List}}
  rpc List{{.Name}}s  (List{{.Name}}sRequest)  returns (List{{.Name}}sResponse);
  {{- end}}
}

message {{.Name}}Response {
  {{.Name}} {{.Lower}} = 1;
}

message {{.Name}} {
  string id = 1;
{{- range $i, $f := .Fields}}
  {{$f.ProtoType}} {{$f.Name}} = {{fieldNum $i 2}};
{{- end}}
  google.protobuf.Timestamp created_at = {{.CreatedAtIdx}};
  google.protobuf.Timestamp updated_at = {{.UpdatedAtIdx}};
}

message Create{{.Name}}Request {
{{- range $i, $f := .Fields}}
  {{$f.ProtoType}} {{$f.Name}} = {{fieldNum $i 1}};
{{- end}}
}

message Get{{.Name}}Request    { string id = 1; }

message Update{{.Name}}Request {
  string id = 1;
{{- range $i, $f := .Fields}}
  {{$f.ProtoType}} {{$f.Name}} = {{fieldNum $i 2}};
{{- end}}
}

message Delete{{.Name}}Request  { string id = 1; }
message Delete{{.Name}}Response {}

message List{{.Name}}sRequest {
  int32 limit  = 1;
  int32 offset = 2;
}

message List{{.Name}}sResponse {
  repeated {{.Name}} {{.Lower}}s = 1;
}
`

// grpcHandlerTmpl generates internal/adapters/grpc/{model}_handler_gen.go
const grpcHandlerTmpl = `// Code generated by scaffold. DO NOT EDIT.

package grpcadapter

import (
	"context"
{{- if .NeedsTime}}
	"time"
{{- end}}

	"{{.ModulePath}}/internal/core/domain"
	"{{.ModulePath}}/internal/core/ports"
	pb "{{.ModulePath}}/internal/adapters/grpc/pb"
	"google.golang.org/grpc"
	"google.golang.org/protobuf/types/known/timestamppb"
)

type {{.Name}}Handler struct {
	pb.Unimplemented{{.Name}}ServiceServer
	service ports.{{.Name}}Service
}

// Register wires this handler into the gRPC server.
func (h *{{.Name}}Handler) Register(s *grpc.Server) {
	pb.Register{{.Name}}ServiceServer(s, h)
}

func New{{.Name}}Handler(service ports.{{.Name}}Service) *{{.Name}}Handler {
	return &{{.Name}}Handler{service: service}
}

{{- if .Ops.Create}}
func (h *{{.Name}}Handler) Create{{.Name}}(ctx context.Context, req *pb.Create{{.Name}}Request) (*pb.{{.Name}}Response, error) {
	p := domain.{{.Name}}{
{{- range .Fields}}
		{{.GoName}}: {{protoToDomain . "req"}},
{{- end}}
	}
	created, err := h.service.Create(ctx, p)
	if err != nil {
		return nil, translateError(err)
	}
	return &pb.{{.Name}}Response{ {{.Name}}: domainToProto{{.Name}}(created)}, nil
}
{{- end}}

{{- if .Ops.Read}}
func (h *{{.Name}}Handler) Get{{.Name}}(ctx context.Context, req *pb.Get{{.Name}}Request) (*pb.{{.Name}}Response, error) {
	v, err := h.service.Get(ctx, req.GetId())
	if err != nil {
		return nil, translateError(err)
	}
	return &pb.{{.Name}}Response{ {{.Name}}: domainToProto{{.Name}}(v)}, nil
}
{{- end}}

{{- if .Ops.Update}}
func (h *{{.Name}}Handler) Update{{.Name}}(ctx context.Context, req *pb.Update{{.Name}}Request) (*pb.{{.Name}}Response, error) {
	p := domain.{{.Name}}{
		ID: req.GetId(),
{{- range .Fields}}
		{{.GoName}}: {{protoToDomain . "req"}},
{{- end}}
	}
	updated, err := h.service.Update(ctx, p)
	if err != nil {
		return nil, translateError(err)
	}
	return &pb.{{.Name}}Response{ {{.Name}}: domainToProto{{.Name}}(updated)}, nil
}
{{- end}}

{{- if .Ops.Delete}}
func (h *{{.Name}}Handler) Delete{{.Name}}(ctx context.Context, req *pb.Delete{{.Name}}Request) (*pb.Delete{{.Name}}Response, error) {
	if err := h.service.Delete(ctx, req.GetId()); err != nil {
		return nil, translateError(err)
	}
	return &pb.Delete{{.Name}}Response{}, nil
}
{{- end}}

{{- if .Ops.List}}
func (h *{{.Name}}Handler) List{{.Name}}s(ctx context.Context, req *pb.List{{.Name}}sRequest) (*pb.List{{.Name}}sResponse, error) {
	items, err := h.service.List(ctx, int(req.GetLimit()), int(req.GetOffset()))
	if err != nil {
		return nil, translateError(err)
	}
	protos := make([]*pb.{{.Name}}, len(items))
	for i := range items {
		protos[i] = domainToProto{{.Name}}(&items[i])
	}
	return &pb.List{{.Name}}sResponse{ {{.Name}}s: protos}, nil
}
{{- end}}

func domainToProto{{.Name}}(p *domain.{{.Name}}) *pb.{{.Name}} {
	if p == nil {
		return nil
	}
	return &pb.{{.Name}}{
		Id: p.ID,
{{- range .Fields}}
		{{.ProtoGoName}}: {{domainToProto . "p"}},
{{- end}}
		CreatedAt: timestamppb.New(p.CreatedAt),
		UpdatedAt: timestamppb.New(p.UpdatedAt),
	}
}
`

// grpcSharedTmpl generates internal/adapters/grpc/shared.go (created once)
const grpcSharedTmpl = `// Code generated by scaffold. DO NOT EDIT.

package grpcadapter

import (
	"errors"

	"{{.ModulePath}}/internal/core/domain"
	"google.golang.org/grpc/codes"
	"google.golang.org/grpc/status"
)

func translateError(err error) error {
	var nfErr *domain.NotFoundError
	if errors.As(err, &nfErr) {
		return status.Errorf(codes.NotFound, "%s", nfErr.Error())
	}
	var aeErr *domain.AlreadyExistsError
	if errors.As(err, &aeErr) {
		return status.Errorf(codes.AlreadyExists, "%s", aeErr.Error())
	}
	var valErr *domain.ValidationError
	if errors.As(err, &valErr) {
		return status.Errorf(codes.InvalidArgument, "%s", valErr.Error())
	}
	var authErr *domain.UnauthorizedError
	if errors.As(err, &authErr) {
		return status.Errorf(codes.Unauthenticated, "%s", authErr.Error())
	}
	var forbErr *domain.ForbiddenError
	if errors.As(err, &forbErr) {
		return status.Errorf(codes.PermissionDenied, "%s", forbErr.Error())
	}
	// Do not leak internal error details to the client; a logging interceptor
	// should record the full error server-side.
	return status.Error(codes.Internal, "internal error")
}
`

// registryTmplSSR regenerates internal/app/registry.go for SSR/SQLite projects.
const registryTmplSSR = `// Code generated by scaffold. DO NOT EDIT.

package app

import (
	"database/sql"
	"log/slog"
{{- if .Models}}

	{{- if .HasHandlers}}
	httpadapter "{{.ModulePath}}/internal/adapters/http"
	{{- end}}
	{{- if and .GRPC .HasHandlers}}
	grpcadapter "{{.ModulePath}}/internal/adapters/grpc"
	{{- end}}
	"{{.ModulePath}}/internal/adapters/store"
	"{{.ModulePath}}/internal/core/ports"
	"{{.ModulePath}}/internal/core/services"
{{- end}}
)

// Stores groups all database outbound adapters.
type Stores struct {
{{- range .Models}}
	{{.Name}} ports.{{.Name}}Store
{{- end}}
}

// Services groups all core business logic services.
type Services struct {
{{- range .Models}}
	{{.Name}} ports.{{.Name}}Service
{{- end}}
}

// Handlers groups all SSR HTTP controllers.
type Handlers struct {
{{- range .Models}}
{{- if not .NoHandler}}
	{{.Name}} *httpadapter.{{.Name}}Handler
{{- end}}
{{- end}}
}

{{- if .GRPC}}

// GRPCHandlers groups all gRPC server handlers.
type GRPCHandlers struct {
{{- range .Models}}
{{- if not .NoHandler}}
	{{.Name}} *grpcadapter.{{.Name}}Handler
{{- end}}
{{- end}}
}
{{- end}}

// Registry is the unified Hexagonal container of the application.
type Registry struct {
	Stores   *Stores
	Services *Services
	Handlers *Handlers
	{{- if .GRPC}}
	GRPCHandlers *GRPCHandlers
	{{- end}}
}

// NewRegistry constructs and wires the entire dependency graph statically at startup.
func NewRegistry(db *sql.DB, logger *slog.Logger) *Registry {
{{- if .Models}}
	st := store.NewStore(db)
{{- end}}

	stores := &Stores{
{{- range .Models}}
		{{.Name}}: &store.{{.Name}}Store{Store: st},
{{- end}}
	}

	svcs := &Services{
{{- range .Models}}
		{{.Name}}: services.New{{.Name}}Service(stores.{{.Name}}, logger),
{{- end}}
	}

	handlers := &Handlers{
{{- range .Models}}
{{- if not .NoHandler}}
		{{.Name}}: httpadapter.New{{.Name}}Handler(svcs.{{.Name}}, logger),
{{- end}}
{{- end}}
	}

	{{- if .GRPC}}
	grpcHandlers := &GRPCHandlers{
{{- range .Models}}
{{- if not .NoHandler}}
		{{.Name}}: grpcadapter.New{{.Name}}Handler(svcs.{{.Name}}),
{{- end}}
{{- end}}
	}
	{{- end}}

	return &Registry{
		Stores:   stores,
		Services: svcs,
		Handlers: handlers,
		{{- if .GRPC}}
		GRPCHandlers: grpcHandlers,
		{{- end}}
	}
}
`

// registryTmplSSRPostgres regenerates internal/app/registry.go for SSR/Postgres projects.
const registryTmplSSRPostgres = `// Code generated by scaffold. DO NOT EDIT.

package app

import (
	"log/slog"

	"github.com/jackc/pgx/v5/pgxpool"
{{- if .Models}}

	{{- if .HasHandlers}}
	httpadapter "{{.ModulePath}}/internal/adapters/http"
	{{- end}}
	{{- if and .GRPC .HasHandlers}}
	grpcadapter "{{.ModulePath}}/internal/adapters/grpc"
	{{- end}}
	"{{.ModulePath}}/internal/adapters/store"
	"{{.ModulePath}}/internal/core/ports"
	"{{.ModulePath}}/internal/core/services"
{{- end}}
)

// Stores groups all database outbound adapters.
type Stores struct {
{{- range .Models}}
	{{.Name}} ports.{{.Name}}Store
{{- end}}
}

// Services groups all core business logic services.
type Services struct {
{{- range .Models}}
	{{.Name}} ports.{{.Name}}Service
{{- end}}
}

// Handlers groups all SSR HTTP controllers.
type Handlers struct {
{{- range .Models}}
{{- if not .NoHandler}}
	{{.Name}} *httpadapter.{{.Name}}Handler
{{- end}}
{{- end}}
}

{{- if .GRPC}}

// GRPCHandlers groups all gRPC server handlers.
type GRPCHandlers struct {
{{- range .Models}}
{{- if not .NoHandler}}
	{{.Name}} *grpcadapter.{{.Name}}Handler
{{- end}}
{{- end}}
}
{{- end}}

// Registry is the unified Hexagonal container of the application.
type Registry struct {
	Stores   *Stores
	Services *Services
	Handlers *Handlers
	{{- if .GRPC}}
	GRPCHandlers *GRPCHandlers
	{{- end}}
}

// NewRegistry constructs and wires the entire dependency graph statically at startup.
func NewRegistry(pool *pgxpool.Pool, logger *slog.Logger) *Registry {
{{- if .Models}}
	st := store.NewStore(pool)
{{- end}}

	stores := &Stores{
{{- range .Models}}
		{{.Name}}: &store.{{.Name}}Store{Store: st},
{{- end}}
	}

	svcs := &Services{
{{- range .Models}}
		{{.Name}}: services.New{{.Name}}Service(stores.{{.Name}}, logger),
{{- end}}
	}

	handlers := &Handlers{
{{- range .Models}}
{{- if not .NoHandler}}
		{{.Name}}: httpadapter.New{{.Name}}Handler(svcs.{{.Name}}, logger),
{{- end}}
{{- end}}
	}

	{{- if .GRPC}}
	grpcHandlers := &GRPCHandlers{
{{- range .Models}}
{{- if not .NoHandler}}
		{{.Name}}: grpcadapter.New{{.Name}}Handler(svcs.{{.Name}}),
{{- end}}
{{- end}}
	}
	{{- end}}

	return &Registry{
		Stores:   stores,
		Services: svcs,
		Handlers: handlers,
		{{- if .GRPC}}
		GRPCHandlers: grpcHandlers,
		{{- end}}
	}
}
`

// ssrHandlerTmpl generates internal/adapters/http/{model}_handler_gen.go for SSR mode.
// Uses [[ ]] for template markers since {{ }} conflicts with html/template syntax.
const ssrHandlerTmpl = `// Code generated by scaffold. DO NOT EDIT.

package http

import (
	{{- if .NeedsJSON}}
	"encoding/json"
	{{- end}}
	"errors"
	"log/slog"
	"net/http"
	{{- if .NeedsStrconv}}
	"strconv"
	{{- end}}
	{{- if .NeedsTime}}
	"time"
	{{- end}}

	"{{.ModulePath}}/internal/core/domain"
	"{{.ModulePath}}/internal/core/ports"
	"{{.ModulePath}}/web/views"
	"github.com/a-h/templ"
	"github.com/go-chi/chi/v5"
)

type {{.Name}}Handler struct {
	service ports.{{.Name}}Service
	logger  *slog.Logger
	prefix  string
}

func New{{.Name}}Handler(service ports.{{.Name}}Service, logger *slog.Logger) *{{.Name}}Handler {
	return &{{.Name}}Handler{service: service, logger: logger, prefix: "/{{.Plural}}"}
}

func (h *{{.Name}}Handler) Prefix() string { return h.prefix }

func (h *{{.Name}}Handler) Router() *chi.Mux {
	r := chi.NewRouter()
	h.RegisterRoutes(r)
	return r
}

func (h *{{.Name}}Handler) RegisterRoutes(r chi.Router) {
	{{- if .Ops.List}}
	r.Get("/", h.List)
	{{- end}}
	{{- if .Ops.Create}}
	r.Get("/new", h.New)
	r.Post("/", h.Create)
	{{- end}}
	{{- if .Ops.Read}}
	r.Get("/{id}", h.Show)
	{{- end}}
	{{- if .Ops.Update}}
	r.Get("/{id}/edit", h.Edit)
	r.Post("/{id}", h.Update)
	{{- end}}
	{{- if .Ops.Delete}}
	r.Delete("/{id}", h.Delete)
	{{- end}}
}

func (h *{{.Name}}Handler) List(w http.ResponseWriter, r *http.Request) {
	items, err := h.service.List(r.Context(), 50, 0)
	if err != nil {
		h.serverError(w, err)
		return
	}
	h.render(w, r, views.{{.Name}}List(items))
}

func (h *{{.Name}}Handler) New(w http.ResponseWriter, r *http.Request) {
	h.render(w, r, views.{{.Name}}Form(nil, true, nil))
}

func (h *{{.Name}}Handler) Show(w http.ResponseWriter, r *http.Request) {
	id := chi.URLParam(r, "id")
	item, err := h.service.Get(r.Context(), id)
	if err != nil {
		h.serverError(w, err)
		return
	}
	h.render(w, r, views.{{.Name}}Show(*item))
}

func (h *{{.Name}}Handler) Edit(w http.ResponseWriter, r *http.Request) {
	id := chi.URLParam(r, "id")
	item, err := h.service.Get(r.Context(), id)
	if err != nil {
		h.serverError(w, err)
		return
	}
	h.render(w, r, views.{{.Name}}Form(item, false, nil))
}

func (h *{{.Name}}Handler) Create(w http.ResponseWriter, r *http.Request) {
	if err := r.ParseForm(); err != nil {
		h.serverError(w, err)
		return
	}
	item := h.bindForm(r, domain.{{.Name}}{})
	if _, err := h.service.Create(r.Context(), item); err != nil {
		h.serverError(w, err)
		return
	}
	http.Redirect(w, r, h.prefix, http.StatusSeeOther)
}

func (h *{{.Name}}Handler) Update(w http.ResponseWriter, r *http.Request) {
	id := chi.URLParam(r, "id")
	if err := r.ParseForm(); err != nil {
		h.serverError(w, err)
		return
	}
	existing, err := h.service.Get(r.Context(), id)
	if err != nil {
		h.serverError(w, err)
		return
	}
	item := h.bindForm(r, *existing)
	item.ID = id
	if _, err := h.service.Update(r.Context(), item); err != nil {
		h.serverError(w, err)
		return
	}
	http.Redirect(w, r, h.prefix+"/"+id, http.StatusSeeOther)
}

func (h *{{.Name}}Handler) Delete(w http.ResponseWriter, r *http.Request) {
	id := chi.URLParam(r, "id")
	if err := h.service.Delete(r.Context(), id); err != nil {
		h.serverError(w, err)
		return
	}
	if r.Header.Get("HX-Request") == "true" {
		w.WriteHeader(http.StatusOK)
		return
	}
	http.Redirect(w, r, h.prefix, http.StatusSeeOther)
}

func (h *{{.Name}}Handler) bindForm(r *http.Request, item domain.{{.Name}}) domain.{{.Name}} {
{{- range .Fields}}
{{- if eq .GoType "string"}}
	item.{{.GoName}} = r.FormValue("{{.Name}}")
{{- else if eq .GoType "*string"}}
	if val, ok := r.Form["{{.Name}}"]; ok {
		if len(val) > 0 && val[0] == "" {
			item.{{.GoName}} = nil
		} else if len(val) > 0 {
			v := val[0]
			item.{{.GoName}} = &v
		}
	}
{{- else if eq .GoType "int"}}
	if v, err := strconv.Atoi(r.FormValue("{{.Name}}")); err == nil { item.{{.GoName}} = v }
{{- else if eq .GoType "*int"}}
	if val, ok := r.Form["{{.Name}}"]; ok {
		if len(val) > 0 && val[0] == "" {
			item.{{.GoName}} = nil
		} else if len(val) > 0 {
			if v, err := strconv.Atoi(val[0]); err == nil { item.{{.GoName}} = &v }
		}
	}
{{- else if eq .GoType "int64"}}
	if v, err := strconv.ParseInt(r.FormValue("{{.Name}}"), 10, 64); err == nil { item.{{.GoName}} = v }
{{- else if eq .GoType "*int64"}}
	if val, ok := r.Form["{{.Name}}"]; ok {
		if len(val) > 0 && val[0] == "" {
			item.{{.GoName}} = nil
		} else if len(val) > 0 {
			if v, err := strconv.ParseInt(val[0], 10, 64); err == nil { item.{{.GoName}} = &v }
		}
	}
{{- else if eq .GoType "float64"}}
	if v, err := strconv.ParseFloat(r.FormValue("{{.Name}}"), 64); err == nil { item.{{.GoName}} = v }
{{- else if eq .GoType "*float64"}}
	if val, ok := r.Form["{{.Name}}"]; ok {
		if len(val) > 0 && val[0] == "" {
			item.{{.GoName}} = nil
		} else if len(val) > 0 {
			if v, err := strconv.ParseFloat(val[0], 64); err == nil { item.{{.GoName}} = &v }
		}
	}
{{- else if eq .GoType "[]string"}}
	if v := r.Form["{{.Name}}"]; len(v) > 0 { item.{{.GoName}} = v }
{{- else if eq .GoType "[]int"}}
	if raw := r.Form["{{.Name}}"]; len(raw) > 0 {
		out := make([]int, 0, len(raw))
		for _, s := range raw {
			if n, err := strconv.Atoi(s); err == nil { out = append(out, n) }
		}
		item.{{.GoName}} = out
	}
{{- else if eq .GoType "[]int64"}}
	if raw := r.Form["{{.Name}}"]; len(raw) > 0 {
		out := make([]int64, 0, len(raw))
		for _, s := range raw {
			if n, err := strconv.ParseInt(s, 10, 64); err == nil { out = append(out, n) }
		}
		item.{{.GoName}} = out
	}
{{- else if eq .GoType "[]float64"}}
	if raw := r.Form["{{.Name}}"]; len(raw) > 0 {
		out := make([]float64, 0, len(raw))
		for _, s := range raw {
			if n, err := strconv.ParseFloat(s, 64); err == nil { out = append(out, n) }
		}
		item.{{.GoName}} = out
	}
{{- else if eq .GoType "[]bool"}}
	if raw := r.Form["{{.Name}}"]; len(raw) > 0 {
		out := make([]bool, 0, len(raw))
		for _, s := range raw {
			out = append(out, s == "on" || s == "true")
		}
		item.{{.GoName}} = out
	}
{{- else if eq .GoType "bool"}}
	item.{{.GoName}} = r.FormValue("{{.Name}}") == "on" || r.FormValue("{{.Name}}") == "true"
{{- else if eq .GoType "*bool"}}
	v := r.FormValue("{{.Name}}") == "on" || r.FormValue("{{.Name}}") == "true"
	item.{{.GoName}} = &v
{{- else if eq .GoType "time.Time"}}
	if raw := r.FormValue("{{.Name}}"); raw != "" {
		for _, layout := range []string{"2006-01-02T15:04", "2006-01-02T15:04:05", time.RFC3339, "2006-01-02"} {
			if t, err := time.Parse(layout, raw); err == nil {
				item.{{.GoName}} = t
				break
			}
		}
	}
{{- else if eq .GoType "*time.Time"}}
	if val, ok := r.Form["{{.Name}}"]; ok {
		if len(val) > 0 && val[0] == "" {
			item.{{.GoName}} = nil
		} else if len(val) > 0 {
			for _, layout := range []string{"2006-01-02T15:04", "2006-01-02T15:04:05", time.RFC3339, "2006-01-02"} {
				if t, err := time.Parse(layout, val[0]); err == nil {
					item.{{.GoName}} = &t
					break
				}
			}
		}
	}
{{- else if eq .GoType "json.RawMessage"}}
	if val, ok := r.Form["{{.Name}}"]; ok {
		if len(val) > 0 && val[0] == "" {
			item.{{.GoName}} = nil
		} else if len(val) > 0 && json.Valid([]byte(val[0])) {
			item.{{.GoName}} = json.RawMessage(val[0])
		}
	}
{{- end}}
{{- end}}
	return item
}

func (h *{{.Name}}Handler) render(w http.ResponseWriter, r *http.Request, c templ.Component) {
	w.Header().Set("Content-Type", "text/html; charset=utf-8")
	if err := c.Render(r.Context(), w); err != nil {
		h.logger.Error("render", "err", err)
		http.Error(w, "Internal Server Error", http.StatusInternalServerError)
	}
}

func (h *{{.Name}}Handler) serverError(w http.ResponseWriter, err error) {
	var nfErr *domain.NotFoundError
	if errors.As(err, &nfErr) {
		http.Error(w, "Not Found", http.StatusNotFound)
		return
	}
	var aeErr *domain.AlreadyExistsError
	if errors.As(err, &aeErr) {
		http.Error(w, aeErr.Error(), http.StatusConflict)
		return
	}
	var valErr *domain.ValidationError
	if errors.As(err, &valErr) {
		http.Error(w, valErr.Error(), http.StatusUnprocessableEntity)
		return
	}
	h.logger.Error("handler error", "err", err)
	http.Error(w, "Internal Server Error", http.StatusInternalServerError)
}
`

// ssrHandlerUserTmpl generates internal/adapters/http/{model}_handler.go (written once).
const ssrHandlerUserTmpl = `package http

// SAFE TO EDIT — scaffold writes this file once and never regenerates it.
// {{.Name}} custom handler methods go here.
`

// ssrViewTmpl generates web/views/{lower}.templ — the templ components for a
// model (List/Form/Show). Rendered with [[ ]] scaffold delimiters so templ's own
// { } expression syntax passes through untouched. display/truthy are package
// helpers (web/views/helpers.go); Layout is the shared layout component.
const ssrViewTmpl = `package views

// The "github.com/a-h/templ" import is added automatically by templ generate
// (templ.SafeURL is referenced below), so it must not be imported here.
import "[[.ModulePath]]/internal/core/domain"

templ [[.Name]]List(items []domain.[[.Name]]) {
	@Layout("[[.Name]]s") {
		<div class="page-header">
			<h1>[[.Name]]s</h1>
			[[- if .Ops.Create]]
			<a href="/[[.Plural]]/new" class="btn btn-primary">New [[.Name]]</a>
			[[- end]]
		</div>
		<div class="card">
			<table>
				<thead>
					<tr>
						[[- range .Fields]]
						<th>[[.GoName]]</th>
						[[- end]]
						<th class="col-actions">Actions</th>
					</tr>
				</thead>
				<tbody>
					if len(items) == 0 {
						<tr>
							<td colspan="[[len .Fields | add 1]]" class="empty">
								No [[.Name]]s yet.
								[[- if .Ops.Create]]
								<a href="/[[.Plural]]/new">Create one →</a>
								[[- end]]
							</td>
						</tr>
					} else {
						for _, item := range items {
							<tr id={ "row-" + item.ID }>
								[[- range .Fields]]
								<td>{ display(item.[[.GoName]]) }</td>
								[[- end]]
								<td class="col-actions">
									[[- if .Ops.Read]]
									<a href={ templ.SafeURL("/[[.Plural]]/" + item.ID) } class="link-muted">View</a>
									[[- end]]
									[[- if .Ops.Update]]
									<a href={ templ.SafeURL("/[[.Plural]]/" + item.ID + "/edit") }>Edit</a>
									[[- end]]
									[[- if .Ops.Delete]]
									<button hx-delete={ "/[[.Plural]]/" + item.ID } hx-target={ "#row-" + item.ID } hx-swap="outerHTML" hx-confirm="Delete this [[.Name]]?" class="link-danger">Delete</button>
									[[- end]]
								</td>
							</tr>
						}
					}
				</tbody>
			</table>
		</div>
	}
}

templ [[.Name]]Form(item *domain.[[.Name]], isNew bool, errors map[string]string) {
	@Layout("[[.Name]]") {
		<div class="narrow">
			<div class="toolbar" style="margin-bottom:1.5rem">
				<a href="/[[.Plural]]" class="link-muted">← Back</a>
				<h1>
					if isNew {
						New [[.Name]]
					} else {
						Edit [[.Name]]
					}
				</h1>
			</div>
			<form
				if isNew {
					action="/[[.Plural]]"
				} else {
					action={ templ.SafeURL("/[[.Plural]]/" + item.ID) }
				}
				method="POST"
				class="card card-body"
			>
				[[- range .Fields]]
				<div class="form-group">
					<label for="[[.Name]]">[[.GoName]]</label>
					[[if or (eq .GoType "bool") (eq .GoType "*bool")]]
					<input id="[[.Name]]" name="[[.Name]]" type="checkbox" if item != nil && truthy(item.[[.GoName]]) { checked }/>
					[[else if eq .GoType "time.Time"]]
					<input id="[[.Name]]" name="[[.Name]]" type="datetime-local" if item != nil { value={ item.[[.GoName]].Format("2006-01-02T15:04") } }/>
					[[else if eq .GoType "*time.Time"]]
					<input id="[[.Name]]" name="[[.Name]]" type="datetime-local" if item != nil && item.[[.GoName]] != nil { value={ item.[[.GoName]].Format("2006-01-02T15:04") } }/>
					[[else]]
					<input id="[[.Name]]" name="[[.Name]]" type="text" if item != nil { value={ display(item.[[.GoName]]) } }/>
					[[end]]
					if errors["[[.Name]]"] != "" {
						<p class="field-error">{ errors["[[.Name]]"] }</p>
					}
				</div>
				[[- end]]
				<div class="form-actions">
					<button type="submit" class="btn btn-primary">
						if isNew {
							Create [[.Name]]
						} else {
							Save changes
						}
					</button>
					<a href="/[[.Plural]]" class="btn btn-secondary">Cancel</a>
				</div>
			</form>
		</div>
	}
}

templ [[.Name]]Show(item domain.[[.Name]]) {
	@Layout("[[.Name]]") {
		<div class="narrow">
			<div class="page-header">
				<div class="toolbar">
					<a href="/[[.Plural]]" class="link-muted">← Back</a>
					<h1>[[.Name]]</h1>
				</div>
				<div class="toolbar-actions">
					[[- if .Ops.Update]]
					<a href={ templ.SafeURL("/[[.Plural]]/" + item.ID + "/edit") } class="btn btn-outline-primary">Edit</a>
					[[- end]]
					[[- if .Ops.Delete]]
					<button hx-delete={ "/[[.Plural]]/" + item.ID } hx-push-url="/[[.Plural]]" hx-target="body" hx-confirm="Delete this [[.Name]]?" class="btn btn-outline-danger">Delete</button>
					[[- end]]
				</div>
			</div>
			<div class="card">
				<dl>
					<div class="detail-row">
						<dt>ID</dt>
						<dd>{ item.ID }</dd>
					</div>
					[[- range .Fields]]
					<div class="detail-row">
						<dt>[[.GoName]]</dt>
						<dd>{ display(item.[[.GoName]]) }</dd>
					</div>
					[[- end]]
					<div class="detail-row">
						<dt>Created</dt>
						<dd>{ item.CreatedAt.Format("2006-01-02 15:04") }</dd>
					</div>
				</dl>
			</div>
		</div>
	}
}
`

// migrationAddSoftDeleteTmpl generates ALTER TABLE ADD COLUMN deleted_at.
const migrationAddSoftDeleteTmpl = `
-- +goose Up
ALTER TABLE {{.TableName}} ADD COLUMN deleted_at {{if .IsPostgres}}TIMESTAMPTZ{{else}}DATETIME{{end}};

-- +goose Down
ALTER TABLE {{.TableName}} DROP COLUMN deleted_at;
`

// migrationDropSoftDeleteTmpl generates ALTER TABLE DROP COLUMN deleted_at.
const migrationDropSoftDeleteTmpl = `
-- +goose Up
ALTER TABLE {{.TableName}} DROP COLUMN deleted_at;

-- +goose Down
ALTER TABLE {{.TableName}} ADD COLUMN deleted_at {{if .IsPostgres}}TIMESTAMPTZ{{else}}DATETIME{{end}};
`

// migrationAddUniqueTogetherTmpl generates CREATE UNIQUE INDEX for unique-together constraints.
const migrationAddUniqueTogetherTmpl = `
-- +goose Up
{{- range .AddedUniqueTogether}}
CREATE UNIQUE INDEX IF NOT EXISTS {{.Name}} ON {{$.TableName}}({{.ColsCS}});
{{- end}}

-- +goose Down
{{- range .AddedUniqueTogether}}
DROP INDEX IF EXISTS {{.Name}};
{{- end}}
`

// migrationDropUniqueTogetherTmpl generates DROP INDEX for unique-together constraints.
const migrationDropUniqueTogetherTmpl = `
-- +goose Up
{{- range .RemovedUniqueTogether}}
DROP INDEX IF EXISTS {{.Name}};
{{- end}}

-- +goose Down
{{- range .RemovedUniqueTogether}}
CREATE UNIQUE INDEX IF NOT EXISTS {{.Name}} ON {{$.TableName}}({{.ColsCS}});
{{- end}}
`


