package generator

// domainTmpl generates internal/core/domain/{model}.go
// Uses scaffold markers so struct fields can be updated without losing Validate().
const domainTmpl = `package domain
{{- if .NeedsTimeImport}}

import "time"
{{- end}}
{{- if .NeedsJSONImport}}

import "encoding/json"
{{- end}}

type {{.Name}} struct {
	// scaffold:fields:start
{{- range .Fields}}
	{{.GoName}} {{.GoType}} ` + "`" + `json:"{{.Name}}"` + "`" + `
{{- end}}
	ID        string    ` + "`" + `json:"id"` + "`" + `
	CreatedAt time.Time ` + "`" + `json:"created_at"` + "`" + `
	UpdatedAt time.Time ` + "`" + `json:"updated_at"` + "`" + `
	// scaffold:fields:end
}

// scaffold:method:GetID:start
func ({{.Receiver}} {{.Name}}) GetID() string { return {{.Receiver}}.ID }
// scaffold:method:GetID:end

// scaffold:method:WithID:start
func ({{.Receiver}} {{.Name}}) WithID(id string) {{.Name}} { {{.Receiver}}.ID = id; return {{.Receiver}} }
// scaffold:method:WithID:end

// Validate enforces business rules on {{.Name}}.
// This method is never overwritten by scaffold — add your rules here.
func ({{.Receiver}} {{.Name}}) Validate() error {
	return nil
}
`

// portsTmpl generates internal/core/ports/{model}.go
const portsTmpl = `// Code generated by scaffold. DO NOT EDIT.

package ports

import "{{.ModulePath}}/internal/core/domain"

type {{.Name}}Store interface {
	CRUDStore[domain.{{.Name}}]
}

type {{.Name}}Service interface {
	CRUDService[domain.{{.Name}}]
}
`

// serviceGenTmpl generates internal/core/services/{model}_service_gen.go
const serviceGenTmpl = `// Code generated by scaffold. DO NOT EDIT.

package services

import (
	"context"
	"log/slog"

	"{{.ModulePath}}/internal/core/domain"
	"{{.ModulePath}}/internal/core/ports"
)

type {{.Name}}Service struct {
	store  ports.{{.Name}}Store
	logger *slog.Logger
}

func New{{.Name}}Service(store ports.{{.Name}}Store, logger *slog.Logger) *{{.Name}}Service {
	return &{{.Name}}Service{store: store, logger: logger}
}

func (s *{{.Name}}Service) Get(ctx context.Context, id string) (*domain.{{.Name}}, error) {
	s.logger.DebugContext(ctx, "fetching {{.Lower}}", "id", id)
	v, err := s.store.Get(ctx, id)
	if err != nil {
		return nil, err
	}
	return &v, nil
}

func (s *{{.Name}}Service) List(ctx context.Context, limit, offset int) ([]domain.{{.Name}}, error) {
	s.logger.DebugContext(ctx, "listing {{.Lower}}s", "limit", limit, "offset", offset)
	return s.store.List(ctx, limit, offset)
}

func (s *{{.Name}}Service) Create(ctx context.Context, p domain.{{.Name}}) (*domain.{{.Name}}, error) {
	s.logger.DebugContext(ctx, "creating {{.Lower}}")
	if err := p.Validate(); err != nil {
		return nil, err
	}
	v, err := s.store.Create(ctx, p)
	if err != nil {
		return nil, err
	}
	return &v, nil
}

func (s *{{.Name}}Service) Update(ctx context.Context, p domain.{{.Name}}) (*domain.{{.Name}}, error) {
	s.logger.DebugContext(ctx, "updating {{.Lower}}", "id", p.ID)
	if err := p.Validate(); err != nil {
		return nil, err
	}
	v, err := s.store.Update(ctx, p)
	if err != nil {
		return nil, err
	}
	return &v, nil
}

func (s *{{.Name}}Service) Delete(ctx context.Context, id string) error {
	s.logger.DebugContext(ctx, "deleting {{.Lower}}", "id", id)
	return s.store.Delete(ctx, id)
}
`

// serviceUserTmpl generates internal/core/services/{model}_service.go (created once)
const serviceUserTmpl = `package services

// {{.Name}}Service custom methods.
// This file is never overwritten by scaffold — add your business logic here.
`

// storeGenTmpl generates internal/adapters/store/{model}_store_gen.go
const storeGenTmpl = `// Code generated by scaffold. DO NOT EDIT.

package store

import (
	"context"
	"database/sql"
	"errors"
{{- if .NeedsJSON}}
	"encoding/json"
{{- end}}

	"{{.ModulePath}}/internal/core/domain"
	"{{.ModulePath}}/internal/core/ports"
)

// {{.Name}}Store implements ports.CRUDStore[domain.{{.Name}}].
type {{.Name}}Store struct{ *Store }

var _ ports.CRUDStore[domain.{{.Name}}] = (*{{.Name}}Store)(nil)

const (
	sql{{.Name}}Get    = ` + "`" + `SELECT {{.SelectCols}} FROM {{.TableName}} WHERE id = ?` + "`" + `
	sql{{.Name}}List   = ` + "`" + `SELECT {{.SelectCols}} FROM {{.TableName}} LIMIT ? OFFSET ?` + "`" + `
	sql{{.Name}}Create = ` + "`" + `INSERT INTO {{.TableName}} ({{.InsertCols}}) VALUES ({{.InsertPlaceholders}}) RETURNING id, created_at, updated_at` + "`" + `
	sql{{.Name}}Update = ` + "`" + `UPDATE {{.TableName}} SET {{.UpdateSet}}, updated_at = CURRENT_TIMESTAMP WHERE id = ? RETURNING created_at, updated_at` + "`" + `
	sql{{.Name}}Delete = ` + "`" + `DELETE FROM {{.TableName}} WHERE id = ?` + "`" + `
)

{{template "scanFunc" .}}

func (s *{{.Name}}Store) Get(ctx context.Context, id string) (domain.{{.Name}}, error) {
	const op = "{{.Name}}Store.Get"
	row := s.db.QueryRowContext(ctx, sql{{.Name}}Get, id)
	notFoundErr := &domain.NotFoundError{Entity: "{{.Name}}", ID: id}
	return queryRow(row, notFoundErr, op, func(r *sql.Row) (domain.{{.Name}}, error) {
		return scan{{.Name}}(r)
	})
}

func (s *{{.Name}}Store) List(ctx context.Context, limit, offset int) ([]domain.{{.Name}}, error) {
	const op = "{{.Name}}Store.List"
	rows, err := s.db.QueryContext(ctx, sql{{.Name}}List, limit, offset)
	if err != nil {
		return nil, DecorateError(err, op)
	}
	return collectRows(rows, op, func(r *sql.Rows) (domain.{{.Name}}, error) {
		return scan{{.Name}}Rows(r)
	})
}

func (s *{{.Name}}Store) Create(ctx context.Context, p domain.{{.Name}}) (domain.{{.Name}}, error) {
	const op = "{{.Name}}Store.Create"
	row := s.db.QueryRowContext(ctx, sql{{.Name}}Create, {{.CreateArgs}})
	if err := row.Scan(&p.ID, &p.CreatedAt, &p.UpdatedAt); err != nil {
		if IsUniqueViolation(err) {
			return domain.{{.Name}}{}, &domain.AlreadyExistsError{Entity: "{{.Name}}"}
		}
		return domain.{{.Name}}{}, DecorateError(err, op)
	}
	return p, nil
}

func (s *{{.Name}}Store) Update(ctx context.Context, p domain.{{.Name}}) (domain.{{.Name}}, error) {
	const op = "{{.Name}}Store.Update"
	row := s.db.QueryRowContext(ctx, sql{{.Name}}Update, {{.UpdateArgs}})
	if err := row.Scan(&p.CreatedAt, &p.UpdatedAt); err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return domain.{{.Name}}{}, &domain.NotFoundError{Entity: "{{.Name}}", ID: p.ID}
		}
		if IsUniqueViolation(err) {
			return domain.{{.Name}}{}, &domain.AlreadyExistsError{Entity: "{{.Name}}"}
		}
		return domain.{{.Name}}{}, DecorateError(err, op)
	}
	return p, nil
}

func (s *{{.Name}}Store) Delete(ctx context.Context, id string) error {
	const op = "{{.Name}}Store.Delete"
	res, err := s.db.ExecContext(ctx, sql{{.Name}}Delete, id)
	if err != nil {
		return DecorateError(err, op)
	}
	n, err := res.RowsAffected()
	if err != nil {
		return DecorateError(err, op)
	}
	if n == 0 {
		return &domain.NotFoundError{Entity: "{{.Name}}", ID: id}
	}
	return nil
}
`

// scanFuncTmpl is a sub-template rendered inside storeGenTmpl.
// Handles regular fields and json.RawMessage two-step scanning.
const scanFuncTmpl = `{{define "scanFunc"}}
func scan{{.Name}}(r *sql.Row) (domain.{{.Name}}, error) {
	var p domain.{{.Name}}
{{- range .Fields}}{{if .IsJSON}}
	var {{.GoName}}Bytes []byte
{{- end}}{{end}}
	err := r.Scan({{.ScanArgs}})
	if err != nil {
		return domain.{{.Name}}{}, err
	}
{{- range .Fields}}{{if .IsJSON}}
	if {{.GoName}}Bytes != nil {
		p.{{.GoName}} = json.RawMessage({{.GoName}}Bytes)
	}
{{- end}}{{end}}
	return p, nil
}

func scan{{.Name}}Rows(r *sql.Rows) (domain.{{.Name}}, error) {
	var p domain.{{.Name}}
{{- range .Fields}}{{if .IsJSON}}
	var {{.GoName}}Bytes []byte
{{- end}}{{end}}
	err := r.Scan({{.ScanArgs}})
	if err != nil {
		return domain.{{.Name}}{}, err
	}
{{- range .Fields}}{{if .IsJSON}}
	if {{.GoName}}Bytes != nil {
		p.{{.GoName}} = json.RawMessage({{.GoName}}Bytes)
	}
{{- end}}{{end}}
	return p, nil
}
{{end}}`

// storeUserTmpl generates internal/adapters/store/{model}_store.go (created once)
const storeUserTmpl = `package store

// {{.Name}} custom store methods.
// This file is never overwritten by scaffold — add your SQL queries here.

// Example:
// func (s *{{.Name}}Store) CustomMethod(ctx context.Context) ([]domain.{{.Name}}, error) {
// 	return nil, nil
// }
`

// schemaTmpl generates the SQL block inserted into schema.sql
const schemaTmpl = `-- scaffold:table:{{.Name}}:start
CREATE TABLE IF NOT EXISTS {{.TableName}} (
    {{.IDDef}},
{{- range .Fields}}
    {{.Name}} {{.SQLType}}{{if .NotNull}} NOT NULL{{end}}{{.SQLModifiers}},
{{- end}}
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);
{{- range .Fields}}{{if .HasIndex}}
CREATE INDEX IF NOT EXISTS idx_{{$.TableName}}_{{.Name}} ON {{$.TableName}}({{.Name}});
{{- end}}{{end}}

CREATE TRIGGER IF NOT EXISTS trg_{{.TableName}}_updated_at
AFTER UPDATE ON {{.TableName}}
FOR EACH ROW
WHEN NEW.updated_at <= OLD.updated_at
BEGIN
    UPDATE {{.TableName}} SET updated_at = CURRENT_TIMESTAMP WHERE id = OLD.id;
END;
-- scaffold:table:{{.Name}}:end`

// migrationCreateTmpl generates the initial CREATE TABLE migration (goose format)
const migrationCreateTmpl = `-- +goose Up
CREATE TABLE IF NOT EXISTS {{.TableName}} (
    {{.IDDef}},
{{- range .Fields}}
    {{.Name}} {{.SQLType}}{{if .NotNull}} NOT NULL{{end}}{{.SQLModifiers}},
{{- end}}
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);
{{- range .Fields}}{{if .HasIndex}}
CREATE INDEX IF NOT EXISTS idx_{{$.TableName}}_{{.Name}} ON {{$.TableName}}({{.Name}});
{{- end}}{{end}}

-- +goose StatementBegin
CREATE TRIGGER IF NOT EXISTS trg_{{.TableName}}_updated_at
AFTER UPDATE ON {{.TableName}}
FOR EACH ROW
WHEN NEW.updated_at <= OLD.updated_at
BEGIN
    UPDATE {{.TableName}} SET updated_at = CURRENT_TIMESTAMP WHERE id = OLD.id;
END;
-- +goose StatementEnd

-- +goose Down
DROP TRIGGER IF EXISTS trg_{{.TableName}}_updated_at;
DROP TABLE IF EXISTS {{.TableName}};
`

// migrationAddColTmpl generates ALTER TABLE ADD COLUMN migration
const migrationAddColTmpl = `-- +goose Up
{{- range .Added}}
ALTER TABLE {{$.TableName}} ADD COLUMN {{.Name}} {{.SQLType}}{{if .NotNull}} NOT NULL{{end}}{{.SQLModifiers}};
{{- end}}

-- +goose Down
{{- range .Added}}
ALTER TABLE {{$.TableName}} DROP COLUMN {{.Name}};
{{- end}}
`

// migrationDropColTmpl generates ALTER TABLE DROP COLUMN migration
const migrationDropColTmpl = `-- +goose Up
{{- range .Removed}}
ALTER TABLE {{$.TableName}} DROP COLUMN {{.Name}};
{{- end}}

-- +goose Down
{{- range .Removed}}
ALTER TABLE {{$.TableName}} ADD COLUMN {{.Name}} {{.SQLType}}{{if .NotNull}} NOT NULL{{end}}{{.SQLModifiers}};
{{- end}}
`

// migrationDropTableTmpl generates the DROP TABLE migration for destroy
const migrationDropTableTmpl = `-- +goose Up
DROP TRIGGER IF EXISTS trg_{{.TableName}}_updated_at;
DROP TABLE IF EXISTS {{.TableName}};

-- +goose Down
CREATE TABLE IF NOT EXISTS {{.TableName}} (
    {{.IDDef}},
{{- range .Fields}}
    {{.Name}} {{.SQLType}}{{if .NotNull}} NOT NULL{{end}}{{.SQLModifiers}},
{{- end}}
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);
{{- range .Fields}}{{if .HasIndex}}
CREATE INDEX IF NOT EXISTS idx_{{$.TableName}}_{{.Name}} ON {{$.TableName}}({{.Name}});
{{- end}}{{end}}
`

// registryTmpl fully regenerates internal/app/registry.go from the manifest
const registryTmpl = `// Code generated by scaffold. DO NOT EDIT.

package app

import (
	"database/sql"
	"log/slog"
{{- if .Models}}

	httpadapter "{{.ModulePath}}/internal/adapters/http"
	{{- if .GRPC}}
	grpcadapter "{{.ModulePath}}/internal/adapters/grpc"
	{{- end}}
	"{{.ModulePath}}/internal/adapters/store"
	"{{.ModulePath}}/internal/core/domain"
	"{{.ModulePath}}/internal/core/ports"
	"{{.ModulePath}}/internal/core/services"
{{- end}}
)

// Stores groups all database outbound adapters.
type Stores struct {
{{- range .Models}}
	{{.Name}} ports.{{.Name}}Store
{{- end}}
}

// Services groups all core business logic services.
type Services struct {
{{- range .Models}}
	{{.Name}} ports.{{.Name}}Service
{{- end}}
}

// Handlers groups all entry point HTTP controllers.
type Handlers struct {
{{- range .Models}}
	{{.Name}} *httpadapter.CRUDHandler[domain.{{.Name}}]
{{- end}}
}

{{- if .GRPC}}

// GRPCHandlers groups all gRPC server handlers.
type GRPCHandlers struct {
{{- range .Models}}
	{{.Name}} *grpcadapter.{{.Name}}Handler
{{- end}}
}
{{- end}}

// Registry is the unified Hexagonal container of the application.
type Registry struct {
	Stores   *Stores
	Services *Services
	Handlers *Handlers
	{{- if .GRPC}}
	GRPCHandlers *GRPCHandlers
	{{- end}}
}

// NewRegistry constructs and wires the entire dependency graph statically at startup.
func NewRegistry(db *sql.DB, logger *slog.Logger) *Registry {
{{- if .Models}}
	st := store.NewStore(db)
{{- end}}

	stores := &Stores{
{{- range .Models}}
		{{.Name}}: &store.{{.Name}}Store{Store: st},
{{- end}}
	}

	svcs := &Services{
{{- range .Models}}
		{{.Name}}: services.New{{.Name}}Service(stores.{{.Name}}, logger),
{{- end}}
	}

	handlers := &Handlers{
{{- range .Models}}
		{{.Name}}: httpadapter.NewCRUDHandler(svcs.{{.Name}}, "{{.Name}}", "", logger),
{{- end}}
	}

	{{- if .GRPC}}
	grpcHandlers := &GRPCHandlers{
{{- range .Models}}
		{{.Name}}: grpcadapter.New{{.Name}}Handler(svcs.{{.Name}}),
{{- end}}
	}
	{{- end}}

	return &Registry{
		Stores:   stores,
		Services: svcs,
		Handlers: handlers,
		{{- if .GRPC}}
		GRPCHandlers: grpcHandlers,
		{{- end}}
	}
}
`

// domainTmplPostgres generates internal/core/domain/{model}.go for Postgres projects
const domainTmplPostgres = `package domain
{{- if .NeedsTimeImport}}

import "time"
{{- end}}
{{- if .NeedsJSONImport}}

import "encoding/json"
{{- end}}

type {{.Name}} struct {
	// scaffold:fields:start
{{- range .Fields}}
	{{.GoName}} {{.GoType}} ` + "`" + `json:"{{.Name}}" db:"{{.Name}}"` + "`" + `
{{- end}}
	ID        string    ` + "`" + `json:"id" db:"id"` + "`" + `
	CreatedAt time.Time ` + "`" + `json:"created_at" db:"created_at"` + "`" + `
	UpdatedAt time.Time ` + "`" + `json:"updated_at" db:"updated_at"` + "`" + `
	// scaffold:fields:end
}

// scaffold:method:GetID:start
func ({{.Receiver}} {{.Name}}) GetID() string { return {{.Receiver}}.ID }
// scaffold:method:GetID:end

// scaffold:method:WithID:start
func ({{.Receiver}} {{.Name}}) WithID(id string) {{.Name}} { {{.Receiver}}.ID = id; return {{.Receiver}} }
// scaffold:method:WithID:end

// Validate enforces business rules on {{.Name}}.
// This method is never overwritten by scaffold — add your rules here.
func ({{.Receiver}} {{.Name}}) Validate() error {
	return nil
}
`

// storeGenTmplPostgres generates internal/adapters/store/{model}_store_gen.go for Postgres
const storeGenTmplPostgres = `// Code generated by scaffold. DO NOT EDIT.

package store

import (
	"context"
	"errors"

	"github.com/jackc/pgx/v5"
	"{{.ModulePath}}/internal/core/domain"
	"{{.ModulePath}}/internal/core/ports"
)

// {{.Name}}Store implements ports.CRUDStore[domain.{{.Name}}].
type {{.Name}}Store struct{ *Store }

var _ ports.CRUDStore[domain.{{.Name}}] = (*{{.Name}}Store)(nil)

const (
	sql{{.Name}}Get    = ` + "`" + `SELECT * FROM {{.TableName}} WHERE id = $1` + "`" + `
	sql{{.Name}}List   = ` + "`" + `SELECT * FROM {{.TableName}} LIMIT $1 OFFSET $2` + "`" + `
	sql{{.Name}}Create = ` + "`" + `INSERT INTO {{.TableName}} ({{.InsertCols}}) VALUES ({{.InsertPlaceholders}}) RETURNING *` + "`" + `
	sql{{.Name}}Update = ` + "`" + `UPDATE {{.TableName}} SET {{.UpdateSet}}, updated_at = NOW() WHERE id = ${{.UpdateIDIdx}} RETURNING *` + "`" + `
	sql{{.Name}}Delete = ` + "`" + `DELETE FROM {{.TableName}} WHERE id = $1` + "`" + `
)

func (s *{{.Name}}Store) Get(ctx context.Context, id string) (domain.{{.Name}}, error) {
	notFound := &domain.NotFoundError{Entity: "{{.Name}}", ID: id}
	v, err := queryOne[domain.{{.Name}}](ctx, s.pool, sql{{.Name}}Get, id)
	if err != nil {
		if errors.Is(err, pgx.ErrNoRows) {
			return domain.{{.Name}}{}, notFound
		}
		return domain.{{.Name}}{}, DecorateError(err, "{{.Name}}Store.Get")
	}
	return v, nil
}

func (s *{{.Name}}Store) List(ctx context.Context, limit, offset int) ([]domain.{{.Name}}, error) {
	return queryMany[domain.{{.Name}}](ctx, s.pool, sql{{.Name}}List, limit, offset)
}

func (s *{{.Name}}Store) Create(ctx context.Context, p domain.{{.Name}}) (domain.{{.Name}}, error) {
	const op = "{{.Name}}Store.Create"
	rows, err := s.pool.Query(ctx, sql{{.Name}}Create, {{.CreateArgs}})
	if err != nil {
		if IsUniqueViolation(err) {
			return domain.{{.Name}}{}, &domain.AlreadyExistsError{Entity: "{{.Name}}"}
		}
		return domain.{{.Name}}{}, DecorateError(err, op)
	}
	result, err := pgx.CollectOneRow(rows, pgx.RowToStructByName[domain.{{.Name}}])
	if err != nil {
		return domain.{{.Name}}{}, DecorateError(err, op)
	}
	return result, nil
}

func (s *{{.Name}}Store) Update(ctx context.Context, p domain.{{.Name}}) (domain.{{.Name}}, error) {
	const op = "{{.Name}}Store.Update"
	rows, err := s.pool.Query(ctx, sql{{.Name}}Update, {{.UpdateArgs}})
	if err != nil {
		if IsUniqueViolation(err) {
			return domain.{{.Name}}{}, &domain.AlreadyExistsError{Entity: "{{.Name}}"}
		}
		return domain.{{.Name}}{}, DecorateError(err, op)
	}
	result, err := pgx.CollectOneRow(rows, pgx.RowToStructByName[domain.{{.Name}}])
	if err != nil {
		if errors.Is(err, pgx.ErrNoRows) {
			return domain.{{.Name}}{}, &domain.NotFoundError{Entity: "{{.Name}}", ID: p.ID}
		}
		return domain.{{.Name}}{}, DecorateError(err, op)
	}
	return result, nil
}

func (s *{{.Name}}Store) Delete(ctx context.Context, id string) error {
	const op = "{{.Name}}Store.Delete"
	tag, err := s.pool.Exec(ctx, sql{{.Name}}Delete, id)
	if err != nil {
		return DecorateError(err, op)
	}
	if tag.RowsAffected() == 0 {
		return &domain.NotFoundError{Entity: "{{.Name}}", ID: id}
	}
	return nil
}
`

// registryTmplPostgres fully regenerates internal/app/registry.go for Postgres projects
const registryTmplPostgres = `// Code generated by scaffold. DO NOT EDIT.

package app

import (
	"log/slog"

	"github.com/jackc/pgx/v5/pgxpool"
{{- if .Models}}

	httpadapter "{{.ModulePath}}/internal/adapters/http"
	{{- if .GRPC}}
	grpcadapter "{{.ModulePath}}/internal/adapters/grpc"
	{{- end}}
	"{{.ModulePath}}/internal/adapters/store"
	"{{.ModulePath}}/internal/core/domain"
	"{{.ModulePath}}/internal/core/ports"
	"{{.ModulePath}}/internal/core/services"
{{- end}}
)

// Stores groups all database outbound adapters.
type Stores struct {
{{- range .Models}}
	{{.Name}} ports.{{.Name}}Store
{{- end}}
}

// Services groups all core business logic services.
type Services struct {
{{- range .Models}}
	{{.Name}} ports.{{.Name}}Service
{{- end}}
}

// Handlers groups all entry point HTTP controllers.
type Handlers struct {
{{- range .Models}}
	{{.Name}} *httpadapter.CRUDHandler[domain.{{.Name}}]
{{- end}}
}

{{- if .GRPC}}

// GRPCHandlers groups all gRPC server handlers.
type GRPCHandlers struct {
{{- range .Models}}
	{{.Name}} *grpcadapter.{{.Name}}Handler
{{- end}}
}
{{- end}}

// Registry is the unified Hexagonal container of the application.
type Registry struct {
	Stores   *Stores
	Services *Services
	Handlers *Handlers
	{{- if .GRPC}}
	GRPCHandlers *GRPCHandlers
	{{- end}}
}

// NewRegistry constructs and wires the entire dependency graph statically at startup.
func NewRegistry(pool *pgxpool.Pool, logger *slog.Logger) *Registry {
{{- if .Models}}
	st := store.NewStore(pool)
{{- end}}

	stores := &Stores{
{{- range .Models}}
		{{.Name}}: &store.{{.Name}}Store{Store: st},
{{- end}}
	}

	svcs := &Services{
{{- range .Models}}
		{{.Name}}: services.New{{.Name}}Service(stores.{{.Name}}, logger),
{{- end}}
	}

	handlers := &Handlers{
{{- range .Models}}
		{{.Name}}: httpadapter.NewCRUDHandler(svcs.{{.Name}}, "{{.Name}}", "", logger),
{{- end}}
	}

	{{- if .GRPC}}
	grpcHandlers := &GRPCHandlers{
{{- range .Models}}
		{{.Name}}: grpcadapter.New{{.Name}}Handler(svcs.{{.Name}}),
{{- end}}
	}
	{{- end}}

	return &Registry{
		Stores:   stores,
		Services: svcs,
		Handlers: handlers,
		{{- if .GRPC}}
		GRPCHandlers: grpcHandlers,
		{{- end}}
	}
}
`

// schemaTmplPostgres generates the SQL block inserted into schema.sql for Postgres
const schemaTmplPostgres = `-- scaffold:table:{{.Name}}:start
CREATE TABLE IF NOT EXISTS {{.TableName}} (
    id UUID PRIMARY KEY DEFAULT uuidv7(),
{{- range .Fields}}
    {{.Name}} {{.SQLType}}{{if .NotNull}} NOT NULL{{end}}{{.SQLModifiers}},
{{- end}}
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
{{range .Fields}}{{if .HasIndex}}
CREATE INDEX{{if .IsJSON}} idx_{{$.TableName}}_{{.Name}} ON {{$.TableName}} USING GIN ({{.Name}});
{{- else}} idx_{{$.TableName}}_{{.Name}} ON {{$.TableName}}({{.Name}});
{{- end}}{{end}}{{end}}
CREATE OR REPLACE FUNCTION trg_set_updated_at()
RETURNS trigger LANGUAGE plpgsql AS $$
BEGIN NEW.updated_at = NOW(); RETURN NEW; END;
$$;

CREATE TRIGGER trg_{{.TableName}}_updated_at
    BEFORE UPDATE ON {{.TableName}}
    FOR EACH ROW EXECUTE FUNCTION trg_set_updated_at();
-- scaffold:table:{{.Name}}:end`

// migrationCreateTmplPostgres generates the initial CREATE TABLE migration for Postgres (goose format)
const migrationCreateTmplPostgres = `-- +goose Up
CREATE TABLE IF NOT EXISTS {{.TableName}} (
    id UUID PRIMARY KEY DEFAULT uuidv7(),
{{- range .Fields}}
    {{.Name}} {{.SQLType}}{{if .NotNull}} NOT NULL{{end}}{{.SQLModifiers}},
{{- end}}
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
{{range .Fields}}{{if .HasIndex}}
CREATE INDEX{{if .IsJSON}} idx_{{$.TableName}}_{{.Name}} ON {{$.TableName}} USING GIN ({{.Name}});
{{- else}} idx_{{$.TableName}}_{{.Name}} ON {{$.TableName}}({{.Name}});
{{- end}}{{end}}{{end}}
-- +goose StatementBegin
CREATE OR REPLACE FUNCTION trg_set_updated_at()
RETURNS trigger LANGUAGE plpgsql AS $$
BEGIN NEW.updated_at = NOW(); RETURN NEW; END;
$$;
-- +goose StatementEnd

CREATE TRIGGER trg_{{.TableName}}_updated_at
    BEFORE UPDATE ON {{.TableName}}
    FOR EACH ROW EXECUTE FUNCTION trg_set_updated_at();

-- +goose Down
DROP TRIGGER IF EXISTS trg_{{.TableName}}_updated_at ON {{.TableName}};
DROP TABLE IF EXISTS {{.TableName}};
`

// migrationDropTableTmplPostgres generates the DROP TABLE migration for destroy on Postgres
const migrationDropTableTmplPostgres = `-- +goose Up
DROP TRIGGER IF EXISTS trg_{{.TableName}}_updated_at ON {{.TableName}};
DROP TABLE IF EXISTS {{.TableName}};

-- +goose Down
CREATE TABLE IF NOT EXISTS {{.TableName}} (
    id UUID PRIMARY KEY DEFAULT uuidv7(),
{{- range .Fields}}
    {{.Name}} {{.SQLType}}{{if .NotNull}} NOT NULL{{end}}{{.SQLModifiers}},
{{- end}}
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
{{range .Fields}}{{if .HasIndex}}
CREATE INDEX{{if .IsJSON}} idx_{{$.TableName}}_{{.Name}} ON {{$.TableName}} USING GIN ({{.Name}});
{{- else}} idx_{{$.TableName}}_{{.Name}} ON {{$.TableName}}({{.Name}});
{{- end}}{{end}}{{end}}
-- +goose StatementBegin
CREATE OR REPLACE FUNCTION trg_set_updated_at()
RETURNS trigger LANGUAGE plpgsql AS $$
BEGIN NEW.updated_at = NOW(); RETURN NEW; END;
$$;
-- +goose StatementEnd

CREATE TRIGGER trg_{{.TableName}}_updated_at
    BEFORE UPDATE ON {{.TableName}}
    FOR EACH ROW EXECUTE FUNCTION trg_set_updated_at();
`

// protoTmpl generates api/proto/v1/{model}.proto
const protoTmpl = `syntax = "proto3";

package api.v1;

option go_package = "{{.ModulePath}}/internal/adapters/grpc/pb";

import "google/protobuf/timestamp.proto";
{{- range .Fields}}{{if eq .ProtoType "bytes"}}
import "google/protobuf/struct.proto";
{{- end}}{{end}}

service {{.Name}}Service {
  rpc Create{{.Name}} (Create{{.Name}}Request) returns ({{.Name}}Response);
  rpc Get{{.Name}}    (Get{{.Name}}Request)    returns ({{.Name}}Response);
  rpc Update{{.Name}} (Update{{.Name}}Request) returns ({{.Name}}Response);
  rpc Delete{{.Name}} (Delete{{.Name}}Request) returns (Delete{{.Name}}Response);
  rpc List{{.Name}}s  (List{{.Name}}sRequest)  returns (List{{.Name}}sResponse);
}

message {{.Name}}Response {
  {{.Name}} {{.Lower}} = 1;
}

message {{.Name}} {
  string id = 1;
{{- range $i, $f := .Fields}}
  {{$f.ProtoType}} {{$f.Name}} = {{fieldNum $i 2}};
{{- end}}
  google.protobuf.Timestamp created_at = {{.CreatedAtIdx}};
  google.protobuf.Timestamp updated_at = {{.UpdatedAtIdx}};
}

message Create{{.Name}}Request {
{{- range $i, $f := .Fields}}
  {{$f.ProtoType}} {{$f.Name}} = {{fieldNum $i 1}};
{{- end}}
}

message Get{{.Name}}Request    { string id = 1; }

message Update{{.Name}}Request {
  string id = 1;
{{- range $i, $f := .Fields}}
  {{$f.ProtoType}} {{$f.Name}} = {{fieldNum $i 2}};
{{- end}}
}

message Delete{{.Name}}Request  { string id = 1; }
message Delete{{.Name}}Response {}

message List{{.Name}}sRequest {
  int32 limit  = 1;
  int32 offset = 2;
}

message List{{.Name}}sResponse {
  repeated {{.Name}} {{.Lower}}s = 1;
}
`

// grpcHandlerTmpl generates internal/adapters/grpc/{model}_handler_gen.go
const grpcHandlerTmpl = `// Code generated by scaffold. DO NOT EDIT.

package grpcadapter

import (
	"context"
{{- if .NeedsTime}}
	"time"
{{- end}}

	"{{.ModulePath}}/internal/core/domain"
	"{{.ModulePath}}/internal/core/ports"
	pb "{{.ModulePath}}/internal/adapters/grpc/pb"
	"google.golang.org/grpc"
	"google.golang.org/protobuf/types/known/timestamppb"
)

type {{.Name}}Handler struct {
	pb.Unimplemented{{.Name}}ServiceServer
	service ports.{{.Name}}Service
}

// Register wires this handler into the gRPC server.
func (h *{{.Name}}Handler) Register(s *grpc.Server) {
	pb.Register{{.Name}}ServiceServer(s, h)
}

func New{{.Name}}Handler(service ports.{{.Name}}Service) *{{.Name}}Handler {
	return &{{.Name}}Handler{service: service}
}

func (h *{{.Name}}Handler) Create{{.Name}}(ctx context.Context, req *pb.Create{{.Name}}Request) (*pb.{{.Name}}Response, error) {
	p := domain.{{.Name}}{
{{- range .Fields}}
		{{.GoName}}: {{protoToDomain . "req"}},
{{- end}}
	}
	created, err := h.service.Create(ctx, p)
	if err != nil {
		return nil, translateError(err)
	}
	return &pb.{{.Name}}Response{ {{.Name}}: domainToProto{{.Name}}(created)}, nil
}

func (h *{{.Name}}Handler) Get{{.Name}}(ctx context.Context, req *pb.Get{{.Name}}Request) (*pb.{{.Name}}Response, error) {
	v, err := h.service.Get(ctx, req.GetId())
	if err != nil {
		return nil, translateError(err)
	}
	return &pb.{{.Name}}Response{ {{.Name}}: domainToProto{{.Name}}(v)}, nil
}

func (h *{{.Name}}Handler) Update{{.Name}}(ctx context.Context, req *pb.Update{{.Name}}Request) (*pb.{{.Name}}Response, error) {
	p := domain.{{.Name}}{
		ID: req.GetId(),
{{- range .Fields}}
		{{.GoName}}: {{protoToDomain . "req"}},
{{- end}}
	}
	updated, err := h.service.Update(ctx, p)
	if err != nil {
		return nil, translateError(err)
	}
	return &pb.{{.Name}}Response{ {{.Name}}: domainToProto{{.Name}}(updated)}, nil
}

func (h *{{.Name}}Handler) Delete{{.Name}}(ctx context.Context, req *pb.Delete{{.Name}}Request) (*pb.Delete{{.Name}}Response, error) {
	if err := h.service.Delete(ctx, req.GetId()); err != nil {
		return nil, translateError(err)
	}
	return &pb.Delete{{.Name}}Response{}, nil
}

func (h *{{.Name}}Handler) List{{.Name}}s(ctx context.Context, req *pb.List{{.Name}}sRequest) (*pb.List{{.Name}}sResponse, error) {
	items, err := h.service.List(ctx, int(req.GetLimit()), int(req.GetOffset()))
	if err != nil {
		return nil, translateError(err)
	}
	protos := make([]*pb.{{.Name}}, len(items))
	for i := range items {
		protos[i] = domainToProto{{.Name}}(&items[i])
	}
	return &pb.List{{.Name}}sResponse{ {{.Name}}s: protos}, nil
}

func domainToProto{{.Name}}(p *domain.{{.Name}}) *pb.{{.Name}} {
	if p == nil {
		return nil
	}
	return &pb.{{.Name}}{
		Id: p.ID,
{{- range .Fields}}
		{{.ProtoGoName}}: {{domainToProto . "p"}},
{{- end}}
		CreatedAt: timestamppb.New(p.CreatedAt),
		UpdatedAt: timestamppb.New(p.UpdatedAt),
	}
}
`

// grpcSharedTmpl generates internal/adapters/grpc/shared.go (created once)
const grpcSharedTmpl = `// Code generated by scaffold. DO NOT EDIT.

package grpcadapter

import (
	"errors"

	"{{.ModulePath}}/internal/core/domain"
	"google.golang.org/grpc/codes"
	"google.golang.org/grpc/status"
)

func translateError(err error) error {
	var nfErr *domain.NotFoundError
	if errors.As(err, &nfErr) {
		return status.Errorf(codes.NotFound, "%s", nfErr.Error())
	}
	var aeErr *domain.AlreadyExistsError
	if errors.As(err, &aeErr) {
		return status.Errorf(codes.AlreadyExists, "%s", aeErr.Error())
	}
	var valErr *domain.ValidationError
	if errors.As(err, &valErr) {
		return status.Errorf(codes.InvalidArgument, "%s", valErr.Error())
	}
	var authErr *domain.UnauthorizedError
	if errors.As(err, &authErr) {
		return status.Errorf(codes.Unauthenticated, "%s", authErr.Error())
	}
	var forbErr *domain.ForbiddenError
	if errors.As(err, &forbErr) {
		return status.Errorf(codes.PermissionDenied, "%s", forbErr.Error())
	}
	return status.Errorf(codes.Internal, "internal error: %v", err)
}
`

// registryTmplSSR regenerates internal/app/registry.go for SSR/SQLite projects.
const registryTmplSSR = `// Code generated by scaffold. DO NOT EDIT.

package app

import (
	"database/sql"
	"html/template"
	"log/slog"
{{- if .Models}}

	httpadapter "{{.ModulePath}}/internal/adapters/http"
	{{- if .GRPC}}
	grpcadapter "{{.ModulePath}}/internal/adapters/grpc"
	{{- end}}
	"{{.ModulePath}}/internal/adapters/store"
	"{{.ModulePath}}/internal/core/ports"
	"{{.ModulePath}}/internal/core/services"
{{- end}}
)

// Stores groups all database outbound adapters.
type Stores struct {
{{- range .Models}}
	{{.Name}} ports.{{.Name}}Store
{{- end}}
}

// Services groups all core business logic services.
type Services struct {
{{- range .Models}}
	{{.Name}} ports.{{.Name}}Service
{{- end}}
}

// Handlers groups all SSR HTTP controllers.
type Handlers struct {
{{- range .Models}}
	{{.Name}} *httpadapter.{{.Name}}Handler
{{- end}}
}

{{- if .GRPC}}

// GRPCHandlers groups all gRPC server handlers.
type GRPCHandlers struct {
{{- range .Models}}
	{{.Name}} *grpcadapter.{{.Name}}Handler
{{- end}}
}
{{- end}}

// Registry is the unified Hexagonal container of the application.
type Registry struct {
	Stores   *Stores
	Services *Services
	Handlers *Handlers
	{{- if .GRPC}}
	GRPCHandlers *GRPCHandlers
	{{- end}}
}

// NewRegistry constructs and wires the entire dependency graph statically at startup.
func NewRegistry(db *sql.DB, logger *slog.Logger, tmpl *template.Template) *Registry {
{{- if .Models}}
	st := store.NewStore(db)
{{- end}}

	stores := &Stores{
{{- range .Models}}
		{{.Name}}: &store.{{.Name}}Store{Store: st},
{{- end}}
	}

	svcs := &Services{
{{- range .Models}}
		{{.Name}}: services.New{{.Name}}Service(stores.{{.Name}}, logger),
{{- end}}
	}

	handlers := &Handlers{
{{- range .Models}}
		{{.Name}}: httpadapter.New{{.Name}}Handler(svcs.{{.Name}}, logger, tmpl),
{{- end}}
	}

	{{- if .GRPC}}
	grpcHandlers := &GRPCHandlers{
{{- range .Models}}
		{{.Name}}: grpcadapter.New{{.Name}}Handler(svcs.{{.Name}}),
{{- end}}
	}
	{{- end}}

	return &Registry{
		Stores:   stores,
		Services: svcs,
		Handlers: handlers,
		{{- if .GRPC}}
		GRPCHandlers: grpcHandlers,
		{{- end}}
	}
}
`

// registryTmplSSRPostgres regenerates internal/app/registry.go for SSR/Postgres projects.
const registryTmplSSRPostgres = `// Code generated by scaffold. DO NOT EDIT.

package app

import (
	"html/template"
	"log/slog"

	"github.com/jackc/pgx/v5/pgxpool"
{{- if .Models}}

	httpadapter "{{.ModulePath}}/internal/adapters/http"
	{{- if .GRPC}}
	grpcadapter "{{.ModulePath}}/internal/adapters/grpc"
	{{- end}}
	"{{.ModulePath}}/internal/adapters/store"
	"{{.ModulePath}}/internal/core/ports"
	"{{.ModulePath}}/internal/core/services"
{{- end}}
)

// Stores groups all database outbound adapters.
type Stores struct {
{{- range .Models}}
	{{.Name}} ports.{{.Name}}Store
{{- end}}
}

// Services groups all core business logic services.
type Services struct {
{{- range .Models}}
	{{.Name}} ports.{{.Name}}Service
{{- end}}
}

// Handlers groups all SSR HTTP controllers.
type Handlers struct {
{{- range .Models}}
	{{.Name}} *httpadapter.{{.Name}}Handler
{{- end}}
}

{{- if .GRPC}}

// GRPCHandlers groups all gRPC server handlers.
type GRPCHandlers struct {
{{- range .Models}}
	{{.Name}} *grpcadapter.{{.Name}}Handler
{{- end}}
}
{{- end}}

// Registry is the unified Hexagonal container of the application.
type Registry struct {
	Stores   *Stores
	Services *Services
	Handlers *Handlers
	{{- if .GRPC}}
	GRPCHandlers *GRPCHandlers
	{{- end}}
}

// NewRegistry constructs and wires the entire dependency graph statically at startup.
func NewRegistry(pool *pgxpool.Pool, logger *slog.Logger, tmpl *template.Template) *Registry {
{{- if .Models}}
	st := store.NewStore(pool)
{{- end}}

	stores := &Stores{
{{- range .Models}}
		{{.Name}}: &store.{{.Name}}Store{Store: st},
{{- end}}
	}

	svcs := &Services{
{{- range .Models}}
		{{.Name}}: services.New{{.Name}}Service(stores.{{.Name}}, logger),
{{- end}}
	}

	handlers := &Handlers{
{{- range .Models}}
		{{.Name}}: httpadapter.New{{.Name}}Handler(svcs.{{.Name}}, logger, tmpl),
{{- end}}
	}

	{{- if .GRPC}}
	grpcHandlers := &GRPCHandlers{
{{- range .Models}}
		{{.Name}}: grpcadapter.New{{.Name}}Handler(svcs.{{.Name}}),
{{- end}}
	}
	{{- end}}

	return &Registry{
		Stores:   stores,
		Services: svcs,
		Handlers: handlers,
		{{- if .GRPC}}
		GRPCHandlers: grpcHandlers,
		{{- end}}
	}
}
`

// ssrHandlerTmpl generates internal/adapters/http/{model}_handler_gen.go for SSR mode.
// Uses [[ ]] for template markers since {{ }} conflicts with html/template syntax.
const ssrHandlerTmpl = `// Code generated by scaffold. DO NOT EDIT.

package http

import (
	"html/template"
	"log/slog"
	"net/http"
	{{- if .NeedsStrconv}}
	"strconv"
	{{- end}}

	"{{.ModulePath}}/internal/core/domain"
	"{{.ModulePath}}/internal/core/ports"
	"github.com/go-chi/chi/v5"
)

type {{.Name}}Handler struct {
	service ports.{{.Name}}Service
	tmpl    *template.Template
	logger  *slog.Logger
	prefix  string
}

func New{{.Name}}Handler(service ports.{{.Name}}Service, logger *slog.Logger, tmpl *template.Template) *{{.Name}}Handler {
	return &{{.Name}}Handler{service: service, tmpl: tmpl, logger: logger, prefix: "/{{.Plural}}"}
}

func (h *{{.Name}}Handler) Prefix() string { return h.prefix }

func (h *{{.Name}}Handler) Router() *chi.Mux {
	r := chi.NewRouter()
	h.RegisterRoutes(r)
	return r
}

func (h *{{.Name}}Handler) RegisterRoutes(r chi.Router) {
	r.Get("/", h.List)
	r.Get("/new", h.New)
	r.Post("/", h.Create)
	r.Get("/{id}", h.Show)
	r.Get("/{id}/edit", h.Edit)
	r.Post("/{id}", h.Update)
	r.Delete("/{id}", h.Delete)
}

type {{.Lower}}ListData struct {
	Title string
	Items []domain.{{.Name}}
}

type {{.Lower}}FormData struct {
	Title  string
	Item   *domain.{{.Name}}
	IsNew  bool
	Errors map[string]string
}

func (h *{{.Name}}Handler) List(w http.ResponseWriter, r *http.Request) {
	items, err := h.service.List(r.Context(), 50, 0)
	if err != nil {
		h.serverError(w, err)
		return
	}
	h.render(w, r, "{{.Plural}}/list.html", {{.Lower}}ListData{Title: "{{.Name}}s", Items: items})
}

func (h *{{.Name}}Handler) New(w http.ResponseWriter, r *http.Request) {
	h.render(w, r, "{{.Plural}}/form.html", {{.Lower}}FormData{Title: "New {{.Name}}", IsNew: true})
}

func (h *{{.Name}}Handler) Show(w http.ResponseWriter, r *http.Request) {
	id := chi.URLParam(r, "id")
	item, err := h.service.Get(r.Context(), id)
	if err != nil {
		h.serverError(w, err)
		return
	}
	h.render(w, r, "{{.Plural}}/show.html", {{.Lower}}FormData{Title: "{{.Name}}", Item: item})
}

func (h *{{.Name}}Handler) Edit(w http.ResponseWriter, r *http.Request) {
	id := chi.URLParam(r, "id")
	item, err := h.service.Get(r.Context(), id)
	if err != nil {
		h.serverError(w, err)
		return
	}
	h.render(w, r, "{{.Plural}}/form.html", {{.Lower}}FormData{Title: "Edit {{.Name}}", Item: item})
}

func (h *{{.Name}}Handler) Create(w http.ResponseWriter, r *http.Request) {
	if err := r.ParseForm(); err != nil {
		h.serverError(w, err)
		return
	}
	item := h.bindForm(r, domain.{{.Name}}{})
	if _, err := h.service.Create(r.Context(), item); err != nil {
		h.serverError(w, err)
		return
	}
	http.Redirect(w, r, h.prefix, http.StatusSeeOther)
}

func (h *{{.Name}}Handler) Update(w http.ResponseWriter, r *http.Request) {
	id := chi.URLParam(r, "id")
	if err := r.ParseForm(); err != nil {
		h.serverError(w, err)
		return
	}
	existing, err := h.service.Get(r.Context(), id)
	if err != nil {
		h.serverError(w, err)
		return
	}
	item := h.bindForm(r, *existing)
	item.ID = id
	if _, err := h.service.Update(r.Context(), item); err != nil {
		h.serverError(w, err)
		return
	}
	http.Redirect(w, r, h.prefix+"/"+id, http.StatusSeeOther)
}

func (h *{{.Name}}Handler) Delete(w http.ResponseWriter, r *http.Request) {
	id := chi.URLParam(r, "id")
	if err := h.service.Delete(r.Context(), id); err != nil {
		h.serverError(w, err)
		return
	}
	if r.Header.Get("HX-Request") == "true" {
		w.WriteHeader(http.StatusOK)
		return
	}
	http.Redirect(w, r, h.prefix, http.StatusSeeOther)
}

func (h *{{.Name}}Handler) bindForm(r *http.Request, item domain.{{.Name}}) domain.{{.Name}} {
{{- range .Fields}}
{{- if eq .GoType "string"}}
	item.{{.GoName}} = r.FormValue("{{.Name}}")
{{- else if eq .GoType "*string"}}
	if v := r.FormValue("{{.Name}}"); v != "" { item.{{.GoName}} = &v }
{{- else if eq .GoType "int"}}
	if v, err := strconv.Atoi(r.FormValue("{{.Name}}")); err == nil { item.{{.GoName}} = v }
{{- else if eq .GoType "*int"}}
	if v, err := strconv.Atoi(r.FormValue("{{.Name}}")); err == nil { item.{{.GoName}} = &v }
{{- else if eq .GoType "int64"}}
	if v, err := strconv.ParseInt(r.FormValue("{{.Name}}"), 10, 64); err == nil { item.{{.GoName}} = v }
{{- else if eq .GoType "*int64"}}
	if v, err := strconv.ParseInt(r.FormValue("{{.Name}}"), 10, 64); err == nil { item.{{.GoName}} = &v }
{{- else if eq .GoType "float64"}}
	if v, err := strconv.ParseFloat(r.FormValue("{{.Name}}"), 64); err == nil { item.{{.GoName}} = v }
{{- else if eq .GoType "*float64"}}
	if v, err := strconv.ParseFloat(r.FormValue("{{.Name}}"), 64); err == nil { item.{{.GoName}} = &v }
{{- else if eq .GoType "bool"}}
	item.{{.GoName}} = r.FormValue("{{.Name}}") == "on" || r.FormValue("{{.Name}}") == "true"
{{- else if eq .GoType "*bool"}}
	if v := r.FormValue("{{.Name}}") == "on" || r.FormValue("{{.Name}}") == "true"; v { item.{{.GoName}} = &v }
{{- end}}
{{- end}}
	return item
}

func (h *{{.Name}}Handler) render(w http.ResponseWriter, r *http.Request, name string, data any) {
	w.Header().Set("Content-Type", "text/html; charset=utf-8")
	if err := h.tmpl.ExecuteTemplate(w, name, data); err != nil {
		h.logger.Error("render template", "name", name, "err", err)
		http.Error(w, "Internal Server Error", http.StatusInternalServerError)
	}
}

func (h *{{.Name}}Handler) serverError(w http.ResponseWriter, err error) {
	h.logger.Error("handler error", "err", err)
	http.Error(w, "Internal Server Error", http.StatusInternalServerError)
}
`

// ssrHandlerUserTmpl generates internal/adapters/http/{model}_handler.go (written once).
const ssrHandlerUserTmpl = `package http

// {{.Name}} custom handler methods — never overwritten by scaffold.
`

// ssrListHTMLTmpl generates web/templates/{plural}/list.html
// Uses [[ ]] as outer delimiters; {{ }} passes through as html/template syntax.
const ssrListHTMLTmpl = `{{template "header" .}}
<div class="flex justify-between items-center mb-6">
  <h1 class="text-2xl font-bold text-gray-900">{{.Title}}</h1>
  <a href="/[[.Plural]]/new"
     class="px-4 py-2 bg-indigo-600 text-white text-sm font-medium rounded-lg hover:bg-indigo-700">
    New [[.Name]]
  </a>
</div>

<div class="bg-white shadow-sm rounded-lg overflow-hidden">
  <table class="min-w-full divide-y divide-gray-200">
    <thead class="bg-gray-50">
      <tr>
        [[- range .Fields]]
        <th class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
          [[.GoName]]
        </th>
        [[- end]]
        <th class="px-6 py-3 text-right text-xs font-medium text-gray-500 uppercase tracking-wider">
          Actions
        </th>
      </tr>
    </thead>
    <tbody class="bg-white divide-y divide-gray-200">
      {{range .Items}}
      <tr id="row-{{.ID}}" class="hover:bg-gray-50">
        [[- range .Fields]]
        <td class="px-6 py-4 whitespace-nowrap text-sm text-gray-900">{{ .[[.GoName]] }}</td>
        [[- end]]
        <td class="px-6 py-4 whitespace-nowrap text-right text-sm space-x-3">
          <a href="/[[.Plural]]/{{.ID}}" class="text-gray-600 hover:text-gray-900">View</a>
          <a href="/[[.Plural]]/{{.ID}}/edit" class="text-indigo-600 hover:text-indigo-900">Edit</a>
          <button hx-delete="/[[.Plural]]/{{.ID}}"
                  hx-target="#row-{{.ID}}"
                  hx-swap="outerHTML"
                  hx-confirm="Delete this [[.Name]]?"
                  class="text-red-600 hover:text-red-900 cursor-pointer">Delete</button>
        </td>
      </tr>
      {{else}}
      <tr>
        <td colspan="[[len .Fields | add 1]]"
            class="px-6 py-8 text-center text-sm text-gray-500">
          No [[.Name]]s yet.
          <a href="/[[.Plural]]/new" class="text-indigo-600 hover:underline ml-1">Create one →</a>
        </td>
      </tr>
      {{end}}
    </tbody>
  </table>
</div>
{{template "footer" .}}`

// ssrFormHTMLTmpl generates web/templates/{plural}/form.html
const ssrFormHTMLTmpl = `{{template "header" .}}
<div class="max-w-2xl">
  <div class="flex items-center gap-4 mb-6">
    <a href="/[[.Plural]]" class="text-gray-500 hover:text-gray-700">← Back</a>
    <h1 class="text-2xl font-bold text-gray-900">{{.Title}}</h1>
  </div>

  <form action="{{if .IsNew}}/[[.Plural]]{{else}}/[[.Plural]]/{{.Item.ID}}{{end}}"
        method="POST"
        class="bg-white shadow-sm rounded-lg p-6 space-y-5">

    [[- range .Fields]]
    <div>
      <label for="[[.Name]]" class="block text-sm font-medium text-gray-700 mb-1">
        [[.GoName]]
      </label>
      <input id="[[.Name]]" name="[[.Name]]"
             type="[[if eq .GoType "bool"]]checkbox[[else if eq .GoType "*bool"]]checkbox[[else]]text[[end]]"
             [[if eq .GoType "bool"]]
             {{if and .Item .Item.[[.GoName]]}}checked{{end}}
             class="rounded border-gray-300 text-indigo-600"
             [[else]]
             value="{{if .Item}}{{ .Item.[[.GoName]] }}{{end}}"
             class="w-full border border-gray-300 rounded-lg px-3 py-2 text-sm focus:outline-none focus:ring-2 focus:ring-indigo-500"
             [[end]]>
      {{if index .Errors "[[.Name]]"}}
      <p class="mt-1 text-xs text-red-600">{{ index .Errors "[[.Name]]" }}</p>
      {{end}}
    </div>
    [[- end]]

    <div class="flex gap-3 pt-2">
      <button type="submit"
              class="px-4 py-2 bg-indigo-600 text-white text-sm font-medium rounded-lg hover:bg-indigo-700">
        {{if .IsNew}}Create [[.Name]]{{else}}Save changes{{end}}
      </button>
      <a href="/[[.Plural]]"
         class="px-4 py-2 bg-white text-gray-700 text-sm font-medium rounded-lg border border-gray-300 hover:bg-gray-50">
        Cancel
      </a>
    </div>
  </form>
</div>
{{template "footer" .}}`

// ssrShowHTMLTmpl generates web/templates/{plural}/show.html
const ssrShowHTMLTmpl = `{{template "header" .}}
<div class="max-w-2xl">
  <div class="flex items-center justify-between mb-6">
    <div class="flex items-center gap-4">
      <a href="/[[.Plural]]" class="text-gray-500 hover:text-gray-700">← Back</a>
      <h1 class="text-2xl font-bold text-gray-900">{{.Title}}</h1>
    </div>
    <div class="flex gap-2">
      <a href="/[[.Plural]]/{{.Item.ID}}/edit"
         class="px-3 py-1.5 text-sm text-indigo-600 border border-indigo-300 rounded-lg hover:bg-indigo-50">
        Edit
      </a>
      <button hx-delete="/[[.Plural]]/{{.Item.ID}}"
              hx-push-url="/[[.Plural]]"
              hx-target="body"
              hx-confirm="Delete this [[.Name]]?"
              class="px-3 py-1.5 text-sm text-red-600 border border-red-300 rounded-lg hover:bg-red-50 cursor-pointer">
        Delete
      </button>
    </div>
  </div>

  <div class="bg-white shadow-sm rounded-lg overflow-hidden">
    <dl class="divide-y divide-gray-200">
      <div class="px-6 py-4 grid grid-cols-3 gap-4">
        <dt class="text-sm font-medium text-gray-500">ID</dt>
        <dd class="text-sm text-gray-900 col-span-2">{{.Item.ID}}</dd>
      </div>
      [[- range .Fields]]
      <div class="px-6 py-4 grid grid-cols-3 gap-4">
        <dt class="text-sm font-medium text-gray-500">[[.GoName]]</dt>
        <dd class="text-sm text-gray-900 col-span-2">{{ .Item.[[.GoName]] }}</dd>
      </div>
      [[- end]]
      <div class="px-6 py-4 grid grid-cols-3 gap-4">
        <dt class="text-sm font-medium text-gray-500">Created</dt>
        <dd class="text-sm text-gray-900 col-span-2">{{.Item.CreatedAt.Format "2006-01-02 15:04"}}</dd>
      </div>
    </dl>
  </div>
</div>
{{template "footer" .}}`

